// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type Agent struct {
	Id                  string `json:"id"`
	DisplayName         string `json:"display_name"`
	Frontmatter         string `json:"frontmatter,omitempty"`
	OwnerId             string `json:"owner_id"`
	ProviderID          int64  `json:"provider_id"`
	Model               string `json:"model"`
	ContextWindow       int    `json:"context_window"`
	MaxToolIterations   int    `json:"max_tool_iterations"`
	Workspace           string `json:"workspace"`
	RestrictToWorkspace bool   `json:"restrict_to_workspace"`
	AgentType           string `json:"agent_type"`
	IsDefault           bool   `json:"is_default"`
	Status              string `json:"status"`
	Emoji               string `json:"emoji,omitempty"`
	AgentDescription    string `json:"agent_description,omitempty"`
	ThinkingLevel       string `json:"thinking_level,omitempty"`
	MaxTokens           int    `json:"max_tokens,omitempty"`
	SelfEvolve          bool   `json:"self_evolve,omitempty"`
	SkillEvolve         bool   `json:"skill_evolve,omitempty"`
	IsShared            bool   `json:"is_shared"`
	CreatedBy           string `json:"created_by,omitempty"`
	CreatedByName       string `json:"created_by_name"`
	CreatedAt           int64  `json:"created_at"`
	UpdatedAt           int64  `json:"updated_at"`
}

type AgentAuthorizationMCP struct {
	ServerID   string `json:"server_id"`
	ServerName string `json:"server_name"`
	Transport  string `json:"transport"`
	Enabled    bool   `json:"enabled"`
}

type AgentAuthorizationSkill struct {
	Id            int64  `json:"id"`
	Name          string `json:"name"`
	Slug          string `json:"slug"`
	Description   string `json:"description"`
	Version       int    `json:"version"`
	Visibility    string `json:"visibility"`
	IsSystem      bool   `json:"is_system"`
	CreatedBy     string `json:"created_by,omitempty"`
	CreatedByName string `json:"created_by_name,omitempty"`
}

type AgentAuthorizationToolPolicy struct {
	Profile        string   `json:"profile,omitempty"`
	Allow          []string `json:"allow,omitempty"`
	Deny           []string `json:"deny,omitempty"`
	AlsoAllow      []string `json:"alsoAllow,omitempty"`
	ToolCallPrefix string   `json:"toolCallPrefix,omitempty"`
}

type AuthResp struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	UserId       string `json:"user_id"`
	Username     string `json:"username"`
	ExpiresIn    int64  `json:"expires_in"`
	TokenType    string `json:"token_type"`
}

type BootstrapFile struct {
	Name    string `json:"name"`              // filename (e.g. "SOUL.md")
	Missing bool   `json:"missing"`           // true if file doesn't exist
	Size    int    `json:"size,omitempty"`    // file size in bytes
	Content string `json:"content,omitempty"` // file content (only in get/set responses)
}

type BuiltinToolDef struct {
	Name    string `json:"name"`
	Display string `json:"display,optional"`
	Desc    string `json:"desc,optional"`
	Enabled bool   `json:"enabled"`
}

type CostSummaryRow struct {
	AgentId           string  `json:"agent_id,omitempty"`
	TotalCost         float64 `json:"total_cost"`
	TotalInputTokens  int     `json:"total_input_tokens"`
	TotalOutputTokens int     `json:"total_output_tokens"`
	TraceCount        int     `json:"trace_count"`
}

type CreateAgentReq struct {
	DisplayName       string `json:"display_name"`
	Frontmatter       string `json:"frontmatter,optional"`
	ProviderID        int64  `json:"provider_id"`
	Model             string `json:"model"`
	AgentDescription  string `json:"agent_description,optional"`
	ContextWindow     int    `json:"context_window,optional"`
	MaxToolIterations int    `json:"max_tool_iterations,optional"`
	Workspace         string `json:"workspace,optional"`
	Emoji             string `json:"emoji,optional"`
	ThinkingLevel     string `json:"thinking_level,optional"`
	MaxTokens         int    `json:"max_tokens,optional"`
	SelfEvolve        bool   `json:"self_evolve,optional"`
	SkillEvolve       bool   `json:"skill_evolve,optional"`
	IsShared          bool   `json:"is_shared,optional"`
}

type CreateAgentResp struct {
	Agent Agent `json:"agent"`
}

type CreateMCPServerReq struct {
	Name        string `json:"name"`
	Description string `json:"description,optional"`
	Transport   string `json:"transport"`
	Command     string `json:"command,optional"`
	Args        string `json:"args,optional"` // JSON array string
	URL         string `json:"url,optional"`
	Headers     string `json:"headers,optional"` // JSON object string
	Env         string `json:"env,optional"`     // JSON object string
	APIKey      string `json:"api_key,optional"`
	ToolPrefix  string `json:"tool_prefix,optional"`
	TimeoutSec  int    `json:"timeout_sec,optional"`
	Settings    string `json:"settings,optional"` // JSON object string
	Enabled     bool   `json:"enabled,optional"`
}

type CreateMCPServerResp struct {
	Server MCPServer `json:"server"`
}

type CreateProviderReq struct {
	Name         string `json:"name"`
	Description  string `json:"description,optional"`
	ProviderType string `json:"provider_type"`
	APIBase      string `json:"api_base"`
	APIKey       string `json:"api_key"`
	Enabled      bool   `json:"enabled"`
}

type CreateProviderResp struct {
	Provider Provider `json:"provider"`
}

type CreateSessionReq struct {
	AgentId string `json:"agent_id"`
}

type CreateSessionResp struct {
	Session Session `json:"session"`
}

type DeleteAgentReq struct {
	AgentId string `path:"agent_id"`
}

type DeleteAgentResp struct {
}

type DeleteMCPServerReq struct {
	Id string `path:"id"`
}

type DeleteMCPServerResp struct {
}

type DeleteMemoryDocumentReq struct {
	AgentID    string `path:"agentID"`
	DocumentID int64  `path:"documentID"`
}

type DeleteMemoryDocumentResp struct {
	Status string `json:"status"`
}

type DeleteProviderReq struct {
	Id int64 `path:"id"`
}

type DeleteProviderResp struct {
}

type DeleteSessionReq struct {
	Id int64 `path:"id"`
}

type DeleteSessionResp struct {
}

type ExportTraceEntry struct {
	Trace     Trace              `json:"trace"`
	Spans     []Span             `json:"spans"`
	SubTraces []ExportTraceEntry `json:"sub_traces,omitempty"`
}

type ExportTraceReq struct {
	TraceId string `path:"traceID"`
}

type ExportTraceResp struct {
}

type GetAgentAuthorizationsReq struct {
	AgentId string `path:"agent_id"`
}

type GetAgentAuthorizationsResp struct {
	Skills     []AgentAuthorizationSkill     `json:"skills"`
	MCPServers []AgentAuthorizationMCP       `json:"mcp_servers"`
	ToolPolicy *AgentAuthorizationToolPolicy `json:"tool_policy,omitempty"`
}

type GetAgentFileReq struct {
	AgentId string `path:"agent_id"`
	Name    string `path:"name"`
}

type GetAgentFileResp struct {
	AgentId string        `json:"agent_id"`
	File    BootstrapFile `json:"file"`
}

type GetAgentReq struct {
	AgentId string `path:"agent_id"`
}

type GetAgentResp struct {
	Agent Agent `json:"agent"`
}

type GetBuiltinToolReq struct {
	Name string `path:"name"`
}

type GetBuiltinToolResp struct {
	Tool BuiltinToolDef `json:"tool"`
}

type GetCostSummaryReq struct {
	AgentId string `form:"agent_id,optional"`
	From    string `form:"from,optional"` // RFC3339 timestamp
	To      string `form:"to,optional"`   // RFC3339 timestamp
}

type GetCostSummaryResp struct {
	Rows []CostSummaryRow `json:"rows"`
}

type GetMCPServerReq struct {
	Id string `path:"id"`
}

type GetMCPServerResp struct {
	Server MCPServer `json:"server"`
}

type GetMeReq struct {
}

type GetMeResp struct {
	User UserResp `json:"user"`
}

type GetMemoryDocumentReq struct {
	AgentID    string `path:"agentID"`
	DocumentID int64  `path:"documentID"`
}

type GetMemoryDocumentResp struct {
	Document MemoryDocument `json:"document"`
}

type GetProviderReq struct {
	Id int64 `path:"id"`
}

type GetProviderResp struct {
	Provider Provider `json:"provider"`
}

type GetSessionReq struct {
	Id int64 `path:"id"`
}

type GetSessionResp struct {
	Session Session `json:"session"`
}

type GetSkillReq struct {
	ID int64 `path:"id"`
}

type GetSkillResp struct {
	Skill   SkillResp `json:"skill"`
	Content string    `json:"content"`
}

type GetSystemHealthReq struct {
}

type GetSystemHealthResp struct {
	Health     SystemHealth `json:"health"`
	QuotaUsage QuotaUsage   `json:"quota_usage"`
}

type GetSystemPromptPreviewReq struct {
	AgentId string `path:"agent_id"`
	Mode    string `form:"mode,optional,default=full"` // full|task|minimal|none
	UserId  string `form:"user_id,optional"`
}

type GetSystemPromptPreviewResp struct {
	Mode       string           `json:"mode"`
	Prompt     string           `json:"prompt"`
	TokenCount int              `json:"token_count"`
	Sections   []PromptSection  `json:"sections"`
	Tools      []ToolDefinition `json:"tools,omitempty"`
}

type GetTraceReq struct {
	TraceId string `path:"traceID"`
}

type GetTraceResp struct {
	Trace Trace  `json:"trace"`
	Spans []Span `json:"spans"`
}

type GetUsageSummaryReq struct {
	Period   string `form:"period,optional,default=24h"`
	AgentID  string `form:"agent_id,optional"`
	Channel  string `form:"channel,optional"`
	Provider string `form:"provider,optional"`
	Model    string `form:"model,optional"`
}

type GetUsageSummaryResp struct {
	Current  UsageSummary `json:"current"`
	Previous UsageSummary `json:"previous"`
}

type GetUsageTimeSeriesReq struct {
	From     string `form:"from"`
	To       string `form:"to"`
	GroupBy  string `form:"group_by,optional,default=hour"`
	AgentID  string `form:"agent_id,optional"`
	Channel  string `form:"channel,optional"`
	Provider string `form:"provider,optional"`
	Model    string `form:"model,optional"`
}

type GetUsageTimeSeriesResp struct {
	Points []UsageTimeSeriesPoint `json:"points"`
}

type GrantMCPServerAgentReq struct {
	Id        string `path:"id"`
	AgentID   string `json:"agent_id"`
	ToolAllow string `json:"tool_allow,optional"` // JSON array string
	ToolDeny  string `json:"tool_deny,optional"`  // JSON array string
}

type GrantMCPServerAgentResp struct {
	Grant MCPAgentGrant `json:"grant"`
}

type GrantSkillAgentReq struct {
	ID      int64  `path:"id"`
	AgentID string `json:"agent_id"`
}

type GrantSkillAgentResp struct {
	Grant SkillAgentGrant `json:"grant"`
}

type IndexAllReq struct {
	AgentID string `path:"agentID"`
}

type IndexAllResp struct {
	Status    string `json:"status"`
	Count     int64  `json:"count,omitempty"`
	Processed int64  `json:"processed,omitempty"`
}

type IndexDocumentReq struct {
	AgentID string `path:"agentID"`
	Path    string `json:"path"`
}

type IndexDocumentResp struct {
	Status string `json:"status"`
	Count  int64  `json:"count,omitempty"`
}

type ListAgentFilesReq struct {
	AgentId string `path:"agent_id"`
}

type ListAgentFilesResp struct {
	AgentId string          `json:"agent_id"`
	Files   []BootstrapFile `json:"files"`
}

type ListAgentMCPServersReq struct {
	AgentID string `path:"agent_id"`
}

type ListAgentMCPServersResp struct {
	Grants []MCPAgentGrant `json:"grants"`
}

type ListAgentMemoryDocumentsReq struct {
	AgentID string `path:"agentID"`
}

type ListAgentSkillsReq struct {
	AgentID string `path:"agent_id"`
}

type ListAgentsReq struct {
}

type ListAgentsResp struct {
	Total  int64   `json:"total"`
	Agents []Agent `json:"agents"`
}

type ListBuiltinToolsReq struct {
}

type ListBuiltinToolsResp struct {
	Tools []BuiltinToolDef `json:"tools"`
}

type ListMCPServerGrantsReq struct {
	Id string `path:"id"`
}

type ListMCPServerGrantsResp struct {
	AgentGrants []MCPAgentGrant `json:"agent_grants"`
}

type ListMCPServerToolsReq struct {
	Id string `path:"id"`
}

type ListMCPServerToolsResp struct {
	Tools []MCPToolInfo `json:"tools"`
}

type ListMCPServersReq struct {
}

type ListMCPServersResp struct {
	Total   int64       `json:"total"`
	Servers []MCPServer `json:"servers"`
}

type ListMemoryChunksReq struct {
	AgentID string `path:"agentID"`
	Path    string `form:"path"`
}

type ListMemoryChunksResp struct {
	Chunks []MemoryChunk `json:"chunks"`
}

type ListMemoryDocumentsReq struct {
}

type ListMemoryDocumentsResp struct {
	Documents []MemoryDocument `json:"documents"`
}

type ListProviderModelsReq struct {
	Id int64 `path:"id"`
}

type ListProviderModelsResp struct {
	Models []string `json:"models"`
}

type ListProvidersReq struct {
}

type ListProvidersResp struct {
	Total     int64      `json:"total"`
	Providers []Provider `json:"providers"`
}

type ListSessionsReq struct {
	Offset int `form:"offset,optional,default=0"`
	Limit  int `form:"limit,optional,default=20"`
}

type ListSessionsResp struct {
	Total    int64     `json:"total"`
	Sessions []Session `json:"sessions"`
}

type ListSkillGrantsReq struct {
	ID int64 `path:"id"`
}

type ListSkillGrantsResp struct {
	AgentGrants []SkillAgentGrant `json:"agent_grants"`
}

type ListSkillsReq struct {
}

type ListTracesReq struct {
	AgentId    string `form:"agent_id,optional"`
	UserId     string `form:"user_id,optional"`
	SessionKey string `form:"session_key,optional"`
	Status     string `form:"status,optional"`
	Channel    string `form:"channel,optional"`
	Limit      int    `form:"limit,optional,default=50"` // max 200
	Offset     int    `form:"offset,optional,default=0"`
}

type ListTracesResp struct {
	Traces []Trace `json:"traces"`
	Total  int64   `json:"total"`
	Limit  int     `json:"limit"`
	Offset int     `json:"offset"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LogoutReq struct {
}

type LogoutResp struct {
}

type MCPAgentGrant struct {
	Id        string `json:"id"`
	ServerID  string `json:"server_id"`
	AgentID   string `json:"agent_id"`
	AgentName string `json:"agent_name,omitempty"` // display name, enriched
	Enabled   bool   `json:"enabled"`
	ToolAllow string `json:"tool_allow,omitempty"` // JSON array string of allowed tool names
	ToolDeny  string `json:"tool_deny,omitempty"`  // JSON array string of denied tool names
	GrantedBy string `json:"granted_by,omitempty"`
	CreatedAt int64  `json:"created_at"`
}

type MCPServer struct {
	Id            string `json:"id"`
	Name          string `json:"name"`
	Description   string `json:"description,omitempty"`
	Transport     string `json:"transport"` // "stdio", "sse", "streamable-http"
	Command       string `json:"command,omitempty"`
	Args          string `json:"args,omitempty"` // JSON array string
	URL           string `json:"url,omitempty"`
	Headers       string `json:"headers,omitempty"` // JSON object string
	Env           string `json:"env,omitempty"`     // JSON object string
	APIKey        string `json:"api_key,omitempty"`
	ToolPrefix    string `json:"tool_prefix,omitempty"`
	TimeoutSec    int    `json:"timeout_sec"`
	Settings      string `json:"settings,omitempty"` // JSON object string
	Enabled       bool   `json:"enabled"`
	IsShared      bool   `json:"is_shared"`
	CreatedBy     string `json:"created_by,omitempty"`
	CreatedByName string `json:"created_by_name"`       // display name, enriched in responses
	AgentCount    int    `json:"agent_count,omitempty"` // enriched in list response
	CreatedAt     int64  `json:"created_at"`
	UpdatedAt     int64  `json:"updated_at"`
}

type MCPToolInfo struct {
	Name        string `json:"name"`
	Description string `json:"description,omitempty"`
}

type MemoryChunk struct {
	ID           string `json:"id,omitempty"`
	StartLine    int64  `json:"start_line"`
	EndLine      int64  `json:"end_line"`
	TextPreview  string `json:"text_preview"`
	HasEmbedding bool   `json:"has_embedding"`
}

type MemoryDocument struct {
	DocumentID int64  `json:"document_id"`
	Path       string `json:"path"`
	Content    string `json:"content"`
	AgentId    string `json:"agent_id,omitempty"`
	UpdatedAt  int64  `json:"updated_at,omitempty"`
	CreatedAt  int64  `json:"created_at,omitempty"`
}

type PromptSection struct {
	Name  string `json:"name"`  // section name from markdown header
	Start int    `json:"start"` // character position start
	End   int    `json:"end"`   // character position end
}

type Provider struct {
	Id            int64  `json:"id"`
	Name          string `json:"name"`
	Description   string `json:"description,omitempty"`
	ProviderType  string `json:"provider_type"`
	APIBase       string `json:"api_base"`
	APIKey        string `json:"api_key"`
	Enabled       bool   `json:"enabled"`
	IsShared      bool   `json:"is_shared"`
	CreatedBy     string `json:"created_by,omitempty"`
	CreatedByName string `json:"created_by_name"`
}

type PutMemoryDocumentReq struct {
	AgentID    string `path:"agentID"`
	DocumentID int64  `path:"documentID"`
	Content    string `json:"content"`
}

type PutMemoryDocumentResp struct {
	Document MemoryDocument `json:"document"`
}

type QuotaUsage struct {
	RequestsToday     int64 `json:"requests_today"`
	InputTokensToday  int64 `json:"input_tokens_today"`
	OutputTokensToday int64 `json:"output_tokens_today"`
	CostToday         int64 `json:"cost_today"`
}

type ReconnectMCPServerReq struct {
	Id string `path:"id"`
}

type ReconnectMCPServerResp struct {
}

type RefreshReq struct {
	RefreshToken string `json:"refresh_token"`
}

type RegisterReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Username string `json:"username"`
}

type RevokeMCPServerAgentGrantReq struct {
	Id      string `path:"id"`
	AgentID string `path:"agent_id"`
}

type RevokeMCPServerAgentGrantResp struct {
}

type RevokeSkillAgentGrantReq struct {
	ID      int64  `path:"id"`
	AgentID string `path:"agent_id"`
}

type RevokeSkillAgentGrantResp struct {
}

type SearchMemoryReq struct {
	AgentID string `path:"agentID"`
	Query   string `json:"query"`
	Limit   int    `json:"limit,optional"`
	Offset  int    `json:"offset,optional"`
}

type SearchMemoryResp struct {
	Results []SearchResult `json:"results"`
	Total   int64          `json:"total,omitempty"`
}

type SearchResult struct {
	Path       string  `json:"path"`
	Content    string  `json:"content"`
	Score      float64 `json:"score,omitempty"`
	Highlights string  `json:"highlights,omitempty"`
}

type Session struct {
	Id           int64  `json:"id"`
	AgentId      string `json:"agent_id"`
	Title        string `json:"title"`
	Preview      string `json:"preview"`
	MessageCount int    `json:"message_count"`
	Created      string `json:"created"`
	Updated      string `json:"updated"`
}

type SetAgentFileReq struct {
	AgentId   string `path:"agent_id"`
	Name      string `path:"name"`
	Content   string `json:"content"`
	Propagate bool   `json:"propagate,optional"` // push change to all existing user instances
}

type SetAgentFileResp struct {
	AgentId    string        `json:"agent_id"`
	File       BootstrapFile `json:"file"`
	Propagated int           `json:"propagated"` // number of instances where file was propagated
}

type SkillAgentGrant struct {
	ID        string `json:"id"`
	SkillID   int64  `json:"skill_id"`
	AgentID   string `json:"agent_id"`
	AgentName string `json:"agent_name,omitempty"`
	Enabled   bool   `json:"enabled"`
	GrantedBy string `json:"granted_by,omitempty"`
	CreatedAt int64  `json:"created_at"`
}

type SkillResp struct {
	ID            int64    `json:"id"`
	Name          string   `json:"name"`
	Slug          string   `json:"slug"`
	Description   string   `json:"description"`
	Enabled       bool     `json:"enabled"`
	Status        string   `json:"status"`
	Version       int      `json:"version"`
	IsSystem      bool     `json:"is_system"`
	Source        string   `json:"source"`
	Visibility    string   `json:"visibility"`
	Tags          []string `json:"tags"`
	MissingDeps   []string `json:"missing_deps"`
	ContentUrl    string   `json:"content_url,omitempty"`
	IsShared      bool     `json:"is_shared"`
	CreatedBy     string   `json:"created_by,omitempty"`
	CreatedByName string   `json:"created_by_name"`
	AgentCount    int      `json:"agent_count,omitempty"`
}

type SkillWithGrantResp struct {
	ID            int64    `json:"id"`
	Name          string   `json:"name"`
	Slug          string   `json:"slug"`
	Description   string   `json:"description"`
	Enabled       bool     `json:"enabled"`
	Status        string   `json:"status"`
	Version       int      `json:"version"`
	IsSystem      bool     `json:"is_system"`
	Source        string   `json:"source"`
	Visibility    string   `json:"visibility"`
	Tags          []string `json:"tags"`
	MissingDeps   []string `json:"missing_deps"`
	Granted       bool     `json:"granted"`
	IsShared      bool     `json:"is_shared"`
	CreatedBy     string   `json:"created_by,omitempty"`
	CreatedByName string   `json:"created_by_name"`
	AgentCount    int      `json:"agent_count,omitempty"`
}

type SkillsResp struct {
	Skills []SkillResp `json:"skills"`
}

type SkillsWithGrantResp struct {
	Skills []SkillWithGrantResp `json:"skills"`
}

type Span struct {
	Id            string  `json:"id"`
	TraceId       string  `json:"trace_id"`
	ParentSpanId  string  `json:"parent_span_id,omitempty"`
	AgentId       string  `json:"agent_id,omitempty"`
	SpanType      string  `json:"span_type"`
	Name          string  `json:"name,omitempty"`
	StartTime     int64   `json:"start_time"`
	EndTime       int64   `json:"end_time,omitempty"`
	DurationMs    int     `json:"duration_ms,omitempty"`
	Status        string  `json:"status"`
	Error         string  `json:"error,omitempty"`
	Level         string  `json:"level,omitempty"`
	Model         string  `json:"model,omitempty"`
	Provider      string  `json:"provider,omitempty"`
	InputTokens   int     `json:"input_tokens,omitempty"`
	OutputTokens  int     `json:"output_tokens,omitempty"`
	TotalCost     float64 `json:"total_cost,omitempty"`
	FinishReason  string  `json:"finish_reason,omitempty"`
	ToolName      string  `json:"tool_name,omitempty"`
	ToolCallId    string  `json:"tool_call_id,omitempty"`
	InputPreview  string  `json:"input_preview,omitempty"`
	OutputPreview string  `json:"output_preview,omitempty"`
	Metadata      string  `json:"metadata,omitempty"`
	CreatedAt     int64   `json:"created_at"`
}

type SystemHealth struct {
	Version         string `json:"version"`
	Uptime          int64  `json:"uptime"`
	Agents          int    `json:"agents"`
	Tools           int    `json:"tools"`
	Sessions        int    `json:"sessions"`
	Providers       int    `json:"providers"`
	Skills          int    `json:"skills"`
	Memory          int    `json:"memory"`
	Document        int    `json:"document"`
	ChannelTotal    int    `json:"channelTotal"`
	ChannelOnline   int    `json:"channelOnline"`
	ChannelDegraded int    `json:"channelDegraded"`
	ChannelFailed   int    `json:"channelFailed"`
}

type TestMCPServerConnectionReq struct {
	Name       string `json:"name"`
	Transport  string `json:"transport"`
	Command    string `json:"command,optional"`
	Args       string `json:"args,optional"` // JSON array string
	URL        string `json:"url,optional"`
	Headers    string `json:"headers,optional"` // JSON object string
	Env        string `json:"env,optional"`     // JSON object string
	APIKey     string `json:"api_key,optional"`
	TimeoutSec int    `json:"timeout_sec,optional"`
}

type TestMCPServerConnectionResp struct {
	Success   bool   `json:"success"`
	ToolCount int    `json:"tool_count,omitempty"`
	Error     string `json:"error,omitempty"`
}

type ToggleSkillGrantResp struct {
	Enabled bool `json:"enabled"`
}

type ToolDefinition struct {
	Name        string `json:"name"`
	Description string `json:"description,omitempty"`
}

type Trace struct {
	Id                string  `json:"id"`
	ParentTraceId     string  `json:"parent_trace_id,omitempty"`
	AgentId           string  `json:"agent_id,omitempty"`
	UserId            string  `json:"user_id,omitempty"`
	SessionId         int64   `json:"session_id,omitempty"`
	RunId             string  `json:"run_id,omitempty"`
	StartTime         int64   `json:"start_time"`
	EndTime           int64   `json:"end_time,omitempty"`
	DurationMs        int     `json:"duration_ms,omitempty"`
	Name              string  `json:"name,omitempty"`
	Channel           string  `json:"channel,omitempty"`
	InputPreview      string  `json:"input_preview,omitempty"`
	OutputPreview     string  `json:"output_preview,omitempty"`
	TotalInputTokens  int     `json:"total_input_tokens"`
	TotalOutputTokens int     `json:"total_output_tokens"`
	TotalCost         float64 `json:"total_cost"`
	SpanCount         int     `json:"span_count"`
	LLMCallCount      int     `json:"llm_call_count"`
	ToolCallCount     int     `json:"tool_call_count"`
	Status            string  `json:"status"`
	Error             string  `json:"error,omitempty"`
	Metadata          string  `json:"metadata,omitempty"`
	Tags              string  `json:"tags,omitempty"`
	TeamId            string  `json:"team_id,omitempty"`
	CreatedAt         int64   `json:"created_at"`
}

type UpdateAgentReq struct {
	AgentId           string `path:"agent_id"`
	DisplayName       string `json:"display_name,optional"`
	Frontmatter       string `json:"frontmatter,optional"`
	ProviderID        int64  `json:"provider_id,optional"`
	Model             string `json:"model,optional"`
	Status            string `json:"status,optional"`
	ContextWindow     int    `json:"context_window,optional"`
	MaxToolIterations int    `json:"max_tool_iterations,optional"`
	Workspace         string `json:"workspace,optional"`
	AgentDescription  string `json:"agent_description,optional"`
	Emoji             string `json:"emoji,optional"`
	ThinkingLevel     string `json:"thinking_level,optional"`
	MaxTokens         int    `json:"max_tokens,optional"`
	SelfEvolve        bool   `json:"self_evolve,optional"`
	SkillEvolve       bool   `json:"skill_evolve,optional"`
	IsShared          bool   `json:"is_shared,optional"`
}

type UpdateAgentResp struct {
	Agent Agent `json:"agent"`
}

type UpdateBuiltinToolReq struct {
	Name    string `path:"name"`
	Enabled bool   `json:"enabled,optional"`
}

type UpdateBuiltinToolResp struct {
	Status string `json:"status"`
}

type UpdateMCPServerReq struct {
	Id          string `path:"id"`
	Name        string `json:"name,optional"`
	Description string `json:"description,optional"`
	Transport   string `json:"transport,optional"`
	Command     string `json:"command,optional"`
	Args        string `json:"args,optional"`
	URL         string `json:"url,optional"`
	Headers     string `json:"headers,optional"`
	Env         string `json:"env,optional"`
	APIKey      string `json:"api_key,optional"`
	ToolPrefix  string `json:"tool_prefix,optional"`
	TimeoutSec  int    `json:"timeout_sec,optional"`
	Settings    string `json:"settings,optional"`
	Enabled     bool   `json:"enabled,optional"`
}

type UpdateMCPServerResp struct {
	Server MCPServer `json:"server"`
}

type UpdateProviderReq struct {
	Id          int64  `path:"id"`
	Name        string `json:"name,omitempty"`
	Description string `json:"description,optional"`
	APIBase     string `json:"api_base,omitempty"`
	APIKey      string `json:"api_key,omitempty"`
	Enabled     bool   `json:"enabled,omitempty"`
}

type UpdateProviderResp struct {
	Provider Provider `json:"provider"`
}

type UpdateSkillReq struct {
	ID          int64  `path:"id"`
	Enabled     bool   `json:"enabled,optional"`
	Name        string `json:"name,optional"`
	Description string `json:"description,optional"`
	Status      string `json:"status,optional"`
	IsShared    bool   `json:"is_shared,optional"`
}

type UpdateSkillResp struct {
	Skill SkillResp `json:"skill"`
}

type UploadSkillReq struct {
}

type UploadSkillResp struct {
	ID         int64  `json:"id"`
	Slug       string `json:"slug"`
	Version    int    `json:"version"`
	Name       string `json:"name"`
	Status     string `json:"status"`
	IsNew      bool   `json:"is_new"`
	ContentUrl string `json:"content_url"`
}

type UsageSummary struct {
	Requests      int     `json:"requests"`
	InputTokens   int64   `json:"input_tokens"`
	OutputTokens  int64   `json:"output_tokens"`
	Cost          float64 `json:"cost"`
	UniqueUsers   int     `json:"unique_users"`
	Errors        int     `json:"errors"`
	LLMCalls      int     `json:"llm_calls"`
	ToolCalls     int     `json:"tool_calls"`
	AvgDurationMS int     `json:"avg_duration_ms"`
}

type UsageTimeSeriesPoint struct {
	BucketTime    string  `json:"bucket_time"`
	RequestCount  int     `json:"request_count"`
	ErrorCount    int     `json:"error_count"`
	UniqueUsers   int     `json:"unique_users"`
	InputTokens   int64   `json:"input_tokens"`
	OutputTokens  int64   `json:"output_tokens"`
	TotalCost     float64 `json:"total_cost"`
	LLMCallCount  int     `json:"llm_call_count"`
	ToolCallCount int     `json:"tool_call_count"`
	AvgDurationMS int     `json:"avg_duration_ms"`
}

type UserResp struct {
	Id        string `json:"id"`
	Email     string `json:"email"`
	Username  string `json:"username"`
	CreatedAt int64  `json:"created_at"`
}

type VerifyProviderReq struct {
	Id    int64  `path:"id"`
	Model string `json:"model"`
}

type VerifyProviderResp struct {
	Valid bool   `json:"valid"`
	Error string `json:"error,omitempty"`
	Note  string `json:"note,omitempty"`
}
