// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type Agent struct {
	Id                  string `json:"id"`
	AgentKey            string `json:"agent_key"`
	DisplayName         string `json:"display_name"`
	Frontmatter         string `json:"frontmatter,omitempty"`
	OwnerId             string `json:"owner_id"`
	Provider            string `json:"provider"`
	Model               string `json:"model"`
	ContextWindow       int    `json:"context_window"`
	MaxToolIterations   int    `json:"max_tool_iterations"`
	Workspace           string `json:"workspace"`
	RestrictToWorkspace bool   `json:"restrict_to_workspace"`
	AgentType           string `json:"agent_type"`
	IsDefault           bool   `json:"is_default"`
	Status              string `json:"status"`
	Emoji               string `json:"emoji,omitempty"`
	AgentDescription    string `json:"agent_description,omitempty"`
	ThinkingLevel       string `json:"thinking_level,omitempty"`
	MaxTokens           int    `json:"max_tokens,omitempty"`
	SelfEvolve          bool   `json:"self_evolve,omitempty"`
	SkillEvolve         bool   `json:"skill_evolve,omitempty"`
	CreatedAt           int64  `json:"created_at"`
	UpdatedAt           int64  `json:"updated_at"`
}

type AuthResp struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	UserId       string `json:"user_id"`
	ExpiresIn    int64  `json:"expires_in"`
	TokenType    string `json:"token_type"`
}

type BuiltinToolDef struct {
	Name    string `json:"name"`
	Display string `json:"display,optional"`
	Desc    string `json:"desc,optional"`
	Enabled bool   `json:"enabled"`
}

type CostSummaryRow struct {
	AgentId           string  `json:"agent_id,omitempty"`
	TotalCost         float64 `json:"total_cost"`
	TotalInputTokens  int     `json:"total_input_tokens"`
	TotalOutputTokens int     `json:"total_output_tokens"`
	TraceCount        int     `json:"trace_count"`
}

type CreateAgentReq struct {
	AgentKey          string `json:"agent_key"`
	DisplayName       string `json:"display_name"`
	Frontmatter       string `json:"frontmatter,optional"`
	Provider          string `json:"provider,optional"`
	Model             string `json:"model"`
	AgentDescription  string `json:"agent_description,optional"`
	ContextWindow     int    `json:"context_window,optional"`
	MaxToolIterations int    `json:"max_tool_iterations,optional"`
	Workspace         string `json:"workspace,optional"`
	Emoji             string `json:"emoji,optional"`
	ThinkingLevel     string `json:"thinking_level,optional"`
	MaxTokens         int    `json:"max_tokens,optional"`
	SelfEvolve        bool   `json:"self_evolve,optional"`
	SkillEvolve       bool   `json:"skill_evolve,optional"`
}

type CreateAgentResp struct {
	Agent Agent `json:"agent"`
}

type CreateProviderReq struct {
	Name         string `json:"name"`
	ProviderType string `json:"provider_type"`
	APIBase      string `json:"api_base"`
	APIKey       string `json:"api_key"`
	DisplayName  string `json:"display_name"`
	Enabled      bool   `json:"enabled"`
}

type CreateProviderResp struct {
	Provider Provider `json:"provider"`
}

type CreateSessionReq struct {
	AgentId string `json:"agent_id"`
	Title   string `json:"title"`
}

type CreateSessionResp struct {
	Session Session `json:"session"`
}

type CreateSkillReq struct {
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Description string `json:"description"`
	Enabled     bool   `json:"enabled"`
}

type DeleteAgentReq struct {
	AgentId string `path:"agent_id"`
}

type DeleteAgentResp struct {
}

type DeleteProviderReq struct {
	Id string `path:"id"`
}

type DeleteProviderResp struct {
}

type DeleteSessionReq struct {
	Id string `path:"id"`
}

type DeleteSessionResp struct {
}

type ExportTraceEntry struct {
	Trace     Trace              `json:"trace"`
	Spans     []Span             `json:"spans"`
	SubTraces []ExportTraceEntry `json:"sub_traces,omitempty"`
}

type ExportTraceReq struct {
	TraceId string `path:"traceID"`
}

type ExportTraceResp struct {
}

type GetAgentReq struct {
	AgentId string `path:"agent_id"`
}

type GetAgentResp struct {
	Agent Agent `json:"agent"`
}

type GetBuiltinToolReq struct {
	Name string `path:"name"`
}

type GetBuiltinToolResp struct {
	Tool BuiltinToolDef `json:"tool"`
}

type GetCostSummaryReq struct {
	AgentId string `form:"agent_id,optional"`
	From    string `form:"from,optional"` // RFC3339 timestamp
	To      string `form:"to,optional"`   // RFC3339 timestamp
}

type GetCostSummaryResp struct {
	Rows []CostSummaryRow `json:"rows"`
}

type GetMeReq struct {
}

type GetMeResp struct {
	User UserResp `json:"user"`
}

type GetProviderReq struct {
	Id string `path:"id"`
}

type GetProviderResp struct {
	Provider Provider `json:"provider"`
}

type GetSessionReq struct {
	Id string `path:"id"`
}

type GetSessionResp struct {
	Session Session `json:"session"`
}

type GetSkillReq struct {
	ID string `path:"id"`
}

type GetSkillResp struct {
	Skill SkillResp `json:"skill"`
}

type GetSystemHealthReq struct {
}

type GetSystemHealthResp struct {
	Health SystemHealth `json:"health"`
}

type GetTraceReq struct {
	TraceId string `path:"traceID"`
}

type GetTraceResp struct {
	Trace Trace  `json:"trace"`
	Spans []Span `json:"spans"`
}

type GetUsageSummaryReq struct {
	Period   string `form:"period,optional,default=24h"`
	AgentID  string `form:"agent_id,optional"`
	Channel  string `form:"channel,optional"`
	Provider string `form:"provider,optional"`
	Model    string `form:"model,optional"`
}

type GetUsageSummaryResp struct {
	Current  UsageSummary `json:"current"`
	Previous UsageSummary `json:"previous"`
}

type GetUsageTimeSeriesReq struct {
	From     string `form:"from"`
	To       string `form:"to"`
	GroupBy  string `form:"group_by,optional,default=hour"`
	AgentID  string `form:"agent_id,optional"`
	Channel  string `form:"channel,optional"`
	Provider string `form:"provider,optional"`
	Model    string `form:"model,optional"`
}

type GetUsageTimeSeriesResp struct {
	Points []UsageTimeSeriesPoint `json:"points"`
}

type GrantSkillReq struct {
	ID      string `path:"id"`
	AgentID string `path:"agent_id"`
	Version int    `json:"version,optional"`
}

type GrantStatusResp struct {
	Status string `json:"status"`
}

type ListAgentSkillsReq struct {
	AgentID string `path:"agent_id"`
}

type ListAgentsReq struct {
}

type ListAgentsResp struct {
	Total  int64   `json:"total"`
	Agents []Agent `json:"agents"`
}

type ListBuiltinToolsReq struct {
}

type ListBuiltinToolsResp struct {
	Tools []BuiltinToolDef `json:"tools"`
}

type ListProviderModelsReq struct {
	Id string `path:"id"`
}

type ListProviderModelsResp struct {
	Models []ProviderModel `json:"models"`
}

type ListProvidersReq struct {
}

type ListProvidersResp struct {
	Total     int64      `json:"total"`
	Providers []Provider `json:"providers"`
}

type ListSessionsReq struct {
	AgentId string `form:"agent_id,optional"`
	Offset  int    `form:"offset,optional,default=0"`
	Limit   int    `form:"limit,optional,default=20"`
}

type ListSessionsResp struct {
	Total    int64     `json:"total"`
	Sessions []Session `json:"sessions"`
}

type ListSkillsReq struct {
}

type ListTracesReq struct {
	AgentId    string `form:"agent_id,optional"`
	UserId     string `form:"user_id,optional"`
	SessionKey string `form:"session_key,optional"`
	Status     string `form:"status,optional"`
	Channel    string `form:"channel,optional"`
	Limit      int    `form:"limit,optional,default=50"` // max 200
	Offset     int    `form:"offset,optional,default=0"`
}

type ListTracesResp struct {
	Traces []Trace `json:"traces"`
	Total  int64   `json:"total"`
	Limit  int     `json:"limit"`
	Offset int     `json:"offset"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LogoutReq struct {
}

type LogoutResp struct {
}

type Provider struct {
	Id           string `json:"id"`
	Name         string `json:"name"`
	ProviderType string `json:"provider_type"`
	APIBase      string `json:"api_base"`
	APIKey       string `json:"api_key"`
	DisplayName  string `json:"display_name"`
	Enabled      bool   `json:"enabled"`
}

type ProviderModel struct {
	Name string `json:"name"`
	Id   string `json:"id"`
}

type RefreshReq struct {
	RefreshToken string `json:"refresh_token"`
}

type RegisterReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Username string `json:"username"`
}

type RevokeSkillReq struct {
	ID      string `path:"id"`
	AgentID string `path:"agent_id"`
}

type RevokeStatusResp struct {
	Status string `json:"status"`
}

type Session struct {
	Id           string `json:"id"`
	AgentId      string `json:"agent_id"`
	Title        string `json:"title"`
	Preview      string `json:"preview"`
	MessageCount int    `json:"message_count"`
	Created      string `json:"created"`
	Updated      string `json:"updated"`
}

type SkillResp struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Slug        string   `json:"slug"`
	Description string   `json:"description"`
	Enabled     bool     `json:"enabled"`
	Status      string   `json:"status"`
	Version     int      `json:"version"`
	IsSystem    bool     `json:"is_system"`
	Source      string   `json:"source"`
	Visibility  string   `json:"visibility"`
	Tags        []string `json:"tags"`
	MissingDeps []string `json:"missing_deps"`
	Author      string   `json:"author"`
}

type SkillWithGrantResp struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Slug        string   `json:"slug"`
	Description string   `json:"description"`
	Enabled     bool     `json:"enabled"`
	Status      string   `json:"status"`
	Version     int      `json:"version"`
	IsSystem    bool     `json:"is_system"`
	Source      string   `json:"source"`
	Visibility  string   `json:"visibility"`
	Tags        []string `json:"tags"`
	MissingDeps []string `json:"missing_deps"`
	Author      string   `json:"author"`
	Granted     bool     `json:"granted"`
}

type SkillsResp struct {
	Skills []SkillResp `json:"skills"`
}

type SkillsWithGrantResp struct {
	Skills []SkillWithGrantResp `json:"skills"`
}

type Span struct {
	Id            string  `json:"id"`
	TraceId       string  `json:"trace_id"`
	ParentSpanId  string  `json:"parent_span_id,omitempty"`
	AgentId       string  `json:"agent_id,omitempty"`
	SpanType      string  `json:"span_type"`
	Name          string  `json:"name,omitempty"`
	StartTime     int64   `json:"start_time"`
	EndTime       int64   `json:"end_time,omitempty"`
	DurationMs    int     `json:"duration_ms,omitempty"`
	Status        string  `json:"status"`
	Error         string  `json:"error,omitempty"`
	Level         string  `json:"level,omitempty"`
	Model         string  `json:"model,omitempty"`
	Provider      string  `json:"provider,omitempty"`
	InputTokens   int     `json:"input_tokens,omitempty"`
	OutputTokens  int     `json:"output_tokens,omitempty"`
	TotalCost     float64 `json:"total_cost,omitempty"`
	FinishReason  string  `json:"finish_reason,omitempty"`
	ToolName      string  `json:"tool_name,omitempty"`
	ToolCallId    string  `json:"tool_call_id,omitempty"`
	InputPreview  string  `json:"input_preview,omitempty"`
	OutputPreview string  `json:"output_preview,omitempty"`
	Metadata      string  `json:"metadata,omitempty"`
	CreatedAt     int64   `json:"created_at"`
}

type SystemHealth struct {
	Version         string `json:"version"`
	Uptime          int64  `json:"uptime"`
	Database        string `json:"database,omitempty"`
	Tools           int    `json:"tools"`
	Sessions        int    `json:"sessions"`
	Providers       int    `json:"providers"`
	ChannelTotal    int    `json:"channelTotal"`
	ChannelOnline   int    `json:"channelOnline"`
	ChannelDegraded int    `json:"channelDegraded"`
	ChannelFailed   int    `json:"channelFailed"`
}

type Trace struct {
	Id                string  `json:"id"`
	ParentTraceId     string  `json:"parent_trace_id,omitempty"`
	AgentId           string  `json:"agent_id,omitempty"`
	UserId            string  `json:"user_id,omitempty"`
	SessionKey        string  `json:"session_key,omitempty"`
	RunId             string  `json:"run_id,omitempty"`
	StartTime         int64   `json:"start_time"`
	EndTime           int64   `json:"end_time,omitempty"`
	DurationMs        int     `json:"duration_ms,omitempty"`
	Name              string  `json:"name,omitempty"`
	Channel           string  `json:"channel,omitempty"`
	InputPreview      string  `json:"input_preview,omitempty"`
	OutputPreview     string  `json:"output_preview,omitempty"`
	TotalInputTokens  int     `json:"total_input_tokens"`
	TotalOutputTokens int     `json:"total_output_tokens"`
	TotalCost         float64 `json:"total_cost"`
	SpanCount         int     `json:"span_count"`
	LLMCallCount      int     `json:"llm_call_count"`
	ToolCallCount     int     `json:"tool_call_count"`
	Status            string  `json:"status"`
	Error             string  `json:"error,omitempty"`
	Metadata          string  `json:"metadata,omitempty"`
	Tags              string  `json:"tags,omitempty"`
	TeamId            string  `json:"team_id,omitempty"`
	CreatedAt         int64   `json:"created_at"`
}

type UpdateAgentReq struct {
	AgentId           string `path:"agent_id"`
	AgentKey          string `json:"agent_key,optional"`
	DisplayName       string `json:"display_name,optional"`
	Frontmatter       string `json:"frontmatter,optional"`
	Provider          string `json:"provider,optional"`
	Model             string `json:"model,optional"`
	Status            string `json:"status,optional"`
	ContextWindow     int    `json:"context_window,optional"`
	MaxToolIterations int    `json:"max_tool_iterations,optional"`
	Workspace         string `json:"workspace,optional"`
	AgentDescription  string `json:"agent_description,optional"`
	Emoji             string `json:"emoji,optional"`
	ThinkingLevel     string `json:"thinking_level,optional"`
	MaxTokens         int    `json:"max_tokens,optional"`
	SelfEvolve        bool   `json:"self_evolve,optional"`
	SkillEvolve       bool   `json:"skill_evolve,optional"`
}

type UpdateAgentResp struct {
	Agent Agent `json:"agent"`
}

type UpdateBuiltinToolReq struct {
	Name    string `path:"name"`
	Enabled bool   `json:"enabled,optional"`
}

type UpdateBuiltinToolResp struct {
	Status string `json:"status"`
}

type UpdateProviderReq struct {
	Id          string `path:"id"`
	Name        string `json:"name,omitempty"`
	APIBase     string `json:"api_base,omitempty"`
	APIKey      string `json:"api_key,omitempty"`
	DisplayName string `json:"display_name,omitempty"`
	Enabled     bool   `json:"enabled,omitempty"`
}

type UpdateProviderResp struct {
	Provider Provider `json:"provider"`
}

type UpdateSkillReq struct {
	ID          string `path:"id"`
	Enabled     bool   `json:"enabled,optional"`
	Name        string `json:"name,optional"`
	Description string `json:"description,optional"`
	Status      string `json:"status,optional"`
}

type UpdateSkillResp struct {
	Skill SkillResp `json:"skill"`
}

type UsageSummary struct {
	Requests      int     `json:"requests"`
	InputTokens   int64   `json:"input_tokens"`
	OutputTokens  int64   `json:"output_tokens"`
	Cost          float64 `json:"cost"`
	UniqueUsers   int     `json:"unique_users"`
	Errors        int     `json:"errors"`
	LLMCalls      int     `json:"llm_calls"`
	ToolCalls     int     `json:"tool_calls"`
	AvgDurationMS int     `json:"avg_duration_ms"`
}

type UsageTimeSeriesPoint struct {
	BucketTime    string  `json:"bucket_time"`
	RequestCount  int     `json:"request_count"`
	ErrorCount    int     `json:"error_count"`
	UniqueUsers   int     `json:"unique_users"`
	InputTokens   int64   `json:"input_tokens"`
	OutputTokens  int64   `json:"output_tokens"`
	TotalCost     float64 `json:"total_cost"`
	LLMCallCount  int     `json:"llm_call_count"`
	ToolCallCount int     `json:"tool_call_count"`
	AvgDurationMS int     `json:"avg_duration_ms"`
}

type UserResp struct {
	Id        string `json:"id"`
	Email     string `json:"email"`
	Username  string `json:"username"`
	CreatedAt int64  `json:"created_at"`
}

type VerifyProviderReq struct {
	Id    string `path:"id"`
	Model string `json:"model"`
}

type VerifyProviderResp struct {
	Valid bool   `json:"valid"`
	Error string `json:"error,omitempty"`
	Note  string `json:"note,omitempty"`
}
