// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type Agent struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Status      string `json:"status"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

type AuthResp struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	ExpiresIn    int64  `json:"expires_in"`
	TokenType    string `json:"token_type"`
}

type CreateAgentReq struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type CreateSessionReq struct {
	AgentId int64 `json:"agent_id"`
}

type DeleteAgentResp struct {
}

type HandleDeleteSessionResp struct {
}

type ListAgentsResp struct {
	Total  int64   `json:"total"`
	Agents []Agent `json:"agents"`
}

type ListSessionsResp struct {
	Total    int64     `json:"total"`
	Sessions []Session `json:"sessions"`
}

type LoginReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LogoutReq struct {
}

type LogoutResp struct {
}

type RefreshReq struct {
	RefreshToken string `json:"refresh_token"`
}

type RegisterReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Username string `json:"username"`
}

type Session struct {
	Id        int64  `json:"id"`
	AgentId   int64  `json:"agent_id"`
	UserId    int64  `json:"user_id"`
	Status    string `json:"status"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type UpdateAgentReq struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Status      string `json:"status"`
}

type UserResp struct {
	Id        int64  `json:"id"`
	Email     string `json:"email"`
	Username  string `json:"username"`
	CreatedAt int64  `json:"created_at"`
}
