// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"github.com/pomclaw/pomclaw/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// List all agents
				Method:  http.MethodGet,
				Path:    "/v1/agents",
				Handler: ListAgentsHandler(serverCtx),
			},
			{
				// Create a new agent
				Method:  http.MethodPost,
				Path:    "/v1/agents",
				Handler: CreateAgentHandler(serverCtx),
			},
			{
				// List memory chunks for agent
				Method:  http.MethodGet,
				Path:    "/v1/agents/:agentID/memory/chunks",
				Handler: ListMemoryChunksHandler(serverCtx),
			},
			{
				// List memory documents for specific agent
				Method:  http.MethodGet,
				Path:    "/v1/agents/:agentID/memory/documents",
				Handler: GetAgentMemoryDocumentsHandler(serverCtx),
			},
			{
				// Get specific memory document by path
				Method:  http.MethodGet,
				Path:    "/v1/agents/:agentID/memory/documents/:documentID",
				Handler: GetMemoryDocumentHandler(serverCtx),
			},
			{
				// Create or update memory document
				Method:  http.MethodPut,
				Path:    "/v1/agents/:agentID/memory/documents/:documentID",
				Handler: PutMemoryDocumentHandler(serverCtx),
			},
			{
				// Delete memory document
				Method:  http.MethodDelete,
				Path:    "/v1/agents/:agentID/memory/documents/:documentID",
				Handler: DeleteMemoryDocumentHandler(serverCtx),
			},
			{
				// Index single document
				Method:  http.MethodPost,
				Path:    "/v1/agents/:agentID/memory/index",
				Handler: IndexDocumentHandler(serverCtx),
			},
			{
				// Index all documents
				Method:  http.MethodPost,
				Path:    "/v1/agents/:agentID/memory/index-all",
				Handler: IndexAllHandler(serverCtx),
			},
			{
				// Search memory documents
				Method:  http.MethodPost,
				Path:    "/v1/agents/:agentID/memory/search",
				Handler: SearchMemoryHandler(serverCtx),
			},
			{
				// Get agent details
				Method:  http.MethodGet,
				Path:    "/v1/agents/:agent_id",
				Handler: GetAgentHandler(serverCtx),
			},
			{
				// Update agent
				Method:  http.MethodPut,
				Path:    "/v1/agents/:agent_id",
				Handler: UpdateAgentHandler(serverCtx),
			},
			{
				// Delete agent
				Method:  http.MethodDelete,
				Path:    "/v1/agents/:agent_id",
				Handler: DeleteAgentHandler(serverCtx),
			},
			{
				// List skills for agent with grant status
				Method:  http.MethodGet,
				Path:    "/v1/agents/:agent_id/skills",
				Handler: ListAgentSkillsHandler(serverCtx),
			},
			{
				// Get cost summary by date, agent, model, or provider
				Method:  http.MethodGet,
				Path:    "/v1/costs/summary",
				Handler: GetCostSummaryHandler(serverCtx),
			},
			{
				// List all memory documents (global)
				Method:  http.MethodGet,
				Path:    "/v1/memory/documents",
				Handler: ListMemoryDocumentsHandler(serverCtx),
			},
			{
				// List all providers
				Method:  http.MethodGet,
				Path:    "/v1/providers",
				Handler: ListProvidersHandler(serverCtx),
			},
			{
				// Create a new provider
				Method:  http.MethodPost,
				Path:    "/v1/providers",
				Handler: CreateProviderHandler(serverCtx),
			},
			{
				// Get provider details
				Method:  http.MethodGet,
				Path:    "/v1/providers/:id",
				Handler: GetProviderHandler(serverCtx),
			},
			{
				// Update provider
				Method:  http.MethodPut,
				Path:    "/v1/providers/:id",
				Handler: UpdateProviderHandler(serverCtx),
			},
			{
				// Delete provider
				Method:  http.MethodDelete,
				Path:    "/v1/providers/:id",
				Handler: DeleteProviderHandler(serverCtx),
			},
			{
				// List provider models
				Method:  http.MethodGet,
				Path:    "/v1/providers/:id/models",
				Handler: ListProviderModelsHandler(serverCtx),
			},
			{
				// Verify provider
				Method:  http.MethodPost,
				Path:    "/v1/providers/:id/verify",
				Handler: VerifyProviderHandler(serverCtx),
			},
			{
				// List all sessions
				Method:  http.MethodGet,
				Path:    "/v1/sessions",
				Handler: HandleListSessionsHandler(serverCtx),
			},
			{
				// Create a new session
				Method:  http.MethodPost,
				Path:    "/v1/sessions",
				Handler: HandleCreateSessionHandler(serverCtx),
			},
			{
				// Get session details
				Method:  http.MethodGet,
				Path:    "/v1/sessions/:id",
				Handler: HandleGetSessionHandler(serverCtx),
			},
			{
				// Delete session
				Method:  http.MethodDelete,
				Path:    "/v1/sessions/:id",
				Handler: HandleDeleteSessionHandler(serverCtx),
			},
			{
				// List all skills
				Method:  http.MethodGet,
				Path:    "/v1/skills",
				Handler: ListSkillsHandler(serverCtx),
			},
			{
				// Create a new skill
				Method:  http.MethodPost,
				Path:    "/v1/skills",
				Handler: CreateSkillHandler(serverCtx),
			},
			{
				// Get skill details
				Method:  http.MethodGet,
				Path:    "/v1/skills/:id",
				Handler: GetSkillHandler(serverCtx),
			},
			{
				// Update skill
				Method:  http.MethodPut,
				Path:    "/v1/skills/:id",
				Handler: UpdateSkillHandler(serverCtx),
			},
			{
				// Grant skill to agent
				Method:  http.MethodPost,
				Path:    "/v1/skills/:id/grant/:agent_id",
				Handler: GrantSkillHandler(serverCtx),
			},
			{
				// Revoke skill from agent
				Method:  http.MethodDelete,
				Path:    "/v1/skills/:id/revoke/:agent_id",
				Handler: RevokeSkillHandler(serverCtx),
			},
			{
				// Get system health status
				Method:  http.MethodGet,
				Path:    "/v1/system/health",
				Handler: GetSystemHealthHandler(serverCtx),
			},
			{
				// List all built-in tools
				Method:  http.MethodGet,
				Path:    "/v1/tools/builtin",
				Handler: ListBuiltinToolsHandler(serverCtx),
			},
			{
				// Get built-in tool details
				Method:  http.MethodGet,
				Path:    "/v1/tools/builtin/:name",
				Handler: GetBuiltinToolHandler(serverCtx),
			},
			{
				// Update built-in tool (enabled, settings)
				Method:  http.MethodPut,
				Path:    "/v1/tools/builtin/:name",
				Handler: UpdateBuiltinToolHandler(serverCtx),
			},
			{
				// List traces with optional filtering
				Method:  http.MethodGet,
				Path:    "/v1/traces",
				Handler: ListTracesHandler(serverCtx),
			},
			{
				// Get trace details with spans
				Method:  http.MethodGet,
				Path:    "/v1/traces/:traceID",
				Handler: GetTraceHandler(serverCtx),
			},
			{
				// Export trace as gzip-compressed JSON
				Method:  http.MethodGet,
				Path:    "/v1/traces/:traceID/export",
				Handler: ExportTraceHandler(serverCtx),
			},
			{
				// Get usage summary
				Method:  http.MethodGet,
				Path:    "/v1/usage/summary",
				Handler: GetUsageSummaryHandler(serverCtx),
			},
			{
				// Get usage time series
				Method:  http.MethodGet,
				Path:    "/v1/usage/timeseries",
				Handler: GetUsageTimeSeriesHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
