// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"github.com/pomclaw/pomclaw/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// List all agents
				Method:  http.MethodGet,
				Path:    "/v1/agents",
				Handler: ListAgentsHandler(serverCtx),
			},
			{
				// Create a new agent
				Method:  http.MethodPost,
				Path:    "/v1/agents",
				Handler: CreateAgentHandler(serverCtx),
			},
			{
				// List memory chunks for agent
				Method:  http.MethodGet,
				Path:    "/v1/agents/:agentID/memory/chunks",
				Handler: ListMemoryChunksHandler(serverCtx),
			},
			{
				// List memory documents for specific agent
				Method:  http.MethodGet,
				Path:    "/v1/agents/:agentID/memory/documents",
				Handler: GetAgentMemoryDocumentsHandler(serverCtx),
			},
			{
				// Get specific memory document by path
				Method:  http.MethodGet,
				Path:    "/v1/agents/:agentID/memory/documents/:documentID",
				Handler: GetMemoryDocumentHandler(serverCtx),
			},
			{
				// Create or update memory document
				Method:  http.MethodPut,
				Path:    "/v1/agents/:agentID/memory/documents/:documentID",
				Handler: PutMemoryDocumentHandler(serverCtx),
			},
			{
				// Delete memory document
				Method:  http.MethodDelete,
				Path:    "/v1/agents/:agentID/memory/documents/:documentID",
				Handler: DeleteMemoryDocumentHandler(serverCtx),
			},
			{
				// Index single document
				Method:  http.MethodPost,
				Path:    "/v1/agents/:agentID/memory/index",
				Handler: IndexDocumentHandler(serverCtx),
			},
			{
				// Index all documents
				Method:  http.MethodPost,
				Path:    "/v1/agents/:agentID/memory/index-all",
				Handler: IndexAllHandler(serverCtx),
			},
			{
				// Search memory documents
				Method:  http.MethodPost,
				Path:    "/v1/agents/:agentID/memory/search",
				Handler: SearchMemoryHandler(serverCtx),
			},
			{
				// Get agent details
				Method:  http.MethodGet,
				Path:    "/v1/agents/:agent_id",
				Handler: GetAgentHandler(serverCtx),
			},
			{
				// Update agent
				Method:  http.MethodPut,
				Path:    "/v1/agents/:agent_id",
				Handler: UpdateAgentHandler(serverCtx),
			},
			{
				// Delete agent
				Method:  http.MethodDelete,
				Path:    "/v1/agents/:agent_id",
				Handler: DeleteAgentHandler(serverCtx),
			},
			{
				// Get agent authorizations (granted skills, MCP servers, tool policy)
				Method:  http.MethodGet,
				Path:    "/v1/agents/:agent_id/authorizations",
				Handler: GetAgentAuthorizationsHandler(serverCtx),
			},
			{
				// List agent bootstrap files (SOUL.md, AGENTS.md, etc.)
				Method:  http.MethodGet,
				Path:    "/v1/agents/:agent_id/files",
				Handler: ListAgentFilesHandler(serverCtx),
			},
			{
				// Get specific agent bootstrap file content
				Method:  http.MethodGet,
				Path:    "/v1/agents/:agent_id/files/:name",
				Handler: GetAgentFileHandler(serverCtx),
			},
			{
				// Set agent bootstrap file content
				Method:  http.MethodPut,
				Path:    "/v1/agents/:agent_id/files/:name",
				Handler: SetAgentFileHandler(serverCtx),
			},
			{
				// List skills for agent with grant status
				Method:  http.MethodGet,
				Path:    "/v1/agents/:agent_id/skills",
				Handler: ListAgentSkillsHandler(serverCtx),
			},
			{
				// Get system prompt preview for agent
				Method:  http.MethodGet,
				Path:    "/v1/agents/:agent_id/system-prompt-preview",
				Handler: GetSystemPromptPreviewHandler(serverCtx),
			},
			{
				// Get cost summary by date, agent, model, or provider
				Method:  http.MethodGet,
				Path:    "/v1/costs/summary",
				Handler: GetCostSummaryHandler(serverCtx),
			},
			{
				// List all MCP servers granted to an agent
				Method:  http.MethodGet,
				Path:    "/v1/mcp/grants/agent/:agent_id",
				Handler: ListAgentMCPServersHandler(serverCtx),
			},
			{
				// List all MCP servers
				Method:  http.MethodGet,
				Path:    "/v1/mcp/servers",
				Handler: ListMCPServersHandler(serverCtx),
			},
			{
				// Create a new MCP server
				Method:  http.MethodPost,
				Path:    "/v1/mcp/servers",
				Handler: CreateMCPServerHandler(serverCtx),
			},
			{
				// Get MCP server details
				Method:  http.MethodGet,
				Path:    "/v1/mcp/servers/:id",
				Handler: GetMCPServerHandler(serverCtx),
			},
			{
				// Update MCP server
				Method:  http.MethodPut,
				Path:    "/v1/mcp/servers/:id",
				Handler: UpdateMCPServerHandler(serverCtx),
			},
			{
				// Delete MCP server
				Method:  http.MethodDelete,
				Path:    "/v1/mcp/servers/:id",
				Handler: DeleteMCPServerHandler(serverCtx),
			},
			{
				// List all agent grants for an MCP server
				Method:  http.MethodGet,
				Path:    "/v1/mcp/servers/:id/grants",
				Handler: ListMCPServerGrantsHandler(serverCtx),
			},
			{
				// Grant MCP server access to an agent
				Method:  http.MethodPost,
				Path:    "/v1/mcp/servers/:id/grants/agent",
				Handler: GrantMCPServerAgentHandler(serverCtx),
			},
			{
				// Revoke MCP server access from an agent
				Method:  http.MethodDelete,
				Path:    "/v1/mcp/servers/:id/grants/agent/:agent_id",
				Handler: RevokeMCPServerAgentGrantHandler(serverCtx),
			},
			{
				// Reconnect MCP server (evict connection pool)
				Method:  http.MethodPost,
				Path:    "/v1/mcp/servers/:id/reconnect",
				Handler: ReconnectMCPServerHandler(serverCtx),
			},
			{
				// List tools for an MCP server
				Method:  http.MethodGet,
				Path:    "/v1/mcp/servers/:id/tools",
				Handler: ListMCPServerToolsHandler(serverCtx),
			},
			{
				// Test MCP server connection without saving
				Method:  http.MethodPost,
				Path:    "/v1/mcp/servers/test",
				Handler: TestMCPServerConnectionHandler(serverCtx),
			},
			{
				// List all memory documents (global)
				Method:  http.MethodGet,
				Path:    "/v1/memory/documents",
				Handler: ListMemoryDocumentsHandler(serverCtx),
			},
			{
				// List all providers
				Method:  http.MethodGet,
				Path:    "/v1/providers",
				Handler: ListProvidersHandler(serverCtx),
			},
			{
				// Create a new provider
				Method:  http.MethodPost,
				Path:    "/v1/providers",
				Handler: CreateProviderHandler(serverCtx),
			},
			{
				// Get provider details
				Method:  http.MethodGet,
				Path:    "/v1/providers/:id",
				Handler: GetProviderHandler(serverCtx),
			},
			{
				// Update provider
				Method:  http.MethodPut,
				Path:    "/v1/providers/:id",
				Handler: UpdateProviderHandler(serverCtx),
			},
			{
				// Delete provider
				Method:  http.MethodDelete,
				Path:    "/v1/providers/:id",
				Handler: DeleteProviderHandler(serverCtx),
			},
			{
				// List provider models
				Method:  http.MethodGet,
				Path:    "/v1/providers/:id/models",
				Handler: ListProviderModelsHandler(serverCtx),
			},
			{
				// Verify provider
				Method:  http.MethodPost,
				Path:    "/v1/providers/:id/verify",
				Handler: VerifyProviderHandler(serverCtx),
			},
			{
				// List all sessions
				Method:  http.MethodGet,
				Path:    "/v1/sessions",
				Handler: ListSessionsHandler(serverCtx),
			},
			{
				// Create a new session
				Method:  http.MethodPost,
				Path:    "/v1/sessions",
				Handler: CreateSessionHandler(serverCtx),
			},
			{
				// Get session details
				Method:  http.MethodGet,
				Path:    "/v1/sessions/:id",
				Handler: GetSessionHandler(serverCtx),
			},
			{
				// Delete session
				Method:  http.MethodDelete,
				Path:    "/v1/sessions/:id",
				Handler: DeleteSessionHandler(serverCtx),
			},
			{
				// List all skills
				Method:  http.MethodGet,
				Path:    "/v1/skills",
				Handler: ListSkillsHandler(serverCtx),
			},
			{
				// Get skill details
				Method:  http.MethodGet,
				Path:    "/v1/skills/:id",
				Handler: GetSkillHandler(serverCtx),
			},
			{
				// Update skill
				Method:  http.MethodPut,
				Path:    "/v1/skills/:id",
				Handler: UpdateSkillHandler(serverCtx),
			},
			{
				// List all agent grants for a skill
				Method:  http.MethodGet,
				Path:    "/v1/skills/:id/grants",
				Handler: ListSkillGrantsHandler(serverCtx),
			},
			{
				// Grant skill to agent
				Method:  http.MethodPost,
				Path:    "/v1/skills/:id/grants/agent",
				Handler: GrantSkillAgentHandler(serverCtx),
			},
			{
				// Revoke skill grant from agent
				Method:  http.MethodDelete,
				Path:    "/v1/skills/:id/grants/agent/:agent_id",
				Handler: RevokeSkillAgentGrantHandler(serverCtx),
			},
			{
				// Upload skill zip package
				Method:  http.MethodPost,
				Path:    "/v1/skills/upload",
				Handler: UploadSkillHandler(serverCtx),
			},
			{
				// Get system health status
				Method:  http.MethodGet,
				Path:    "/v1/system/health",
				Handler: GetSystemHealthHandler(serverCtx),
			},
			{
				// List all built-in tools
				Method:  http.MethodGet,
				Path:    "/v1/tools/builtin",
				Handler: ListBuiltinToolsHandler(serverCtx),
			},
			{
				// Get built-in tool details
				Method:  http.MethodGet,
				Path:    "/v1/tools/builtin/:name",
				Handler: GetBuiltinToolHandler(serverCtx),
			},
			{
				// Update built-in tool (enabled, settings)
				Method:  http.MethodPut,
				Path:    "/v1/tools/builtin/:name",
				Handler: UpdateBuiltinToolHandler(serverCtx),
			},
			{
				// List traces with optional filtering
				Method:  http.MethodGet,
				Path:    "/v1/traces",
				Handler: ListTracesHandler(serverCtx),
			},
			{
				// Get trace details with spans
				Method:  http.MethodGet,
				Path:    "/v1/traces/:traceID",
				Handler: GetTraceHandler(serverCtx),
			},
			{
				// Export trace as gzip-compressed JSON
				Method:  http.MethodGet,
				Path:    "/v1/traces/:traceID/export",
				Handler: ExportTraceHandler(serverCtx),
			},
			{
				// Get usage summary
				Method:  http.MethodGet,
				Path:    "/v1/usage/summary",
				Handler: GetUsageSummaryHandler(serverCtx),
			},
			{
				// Get usage time series
				Method:  http.MethodGet,
				Path:    "/v1/usage/timeseries",
				Handler: GetUsageTimeSeriesHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/pomclaw-api"),
	)
}
