export const ROUTES = {
  LOGIN: "/login",
  OVERVIEW: "/overview",
  CHAT: "/chat",
  CHAT_PATTERN: "/chat/:sessionKey?",
  AGENTS: "/agents",
  AGENT_DETAIL: "/agents/:id",
  IMPORT_EXPORT: "/import-export",
  SESSIONS: "/sessions",
  SESSION_DETAIL: "/sessions/:key",
  SKILLS: "/skills",
  SKILL_DETAIL: "/skills/:id",
  CONFIG: "/config",
  TRACES: "/traces",
  TRACE_DETAIL: "/traces/:id",
  PROVIDERS: "/providers",
  PROVIDER_DETAIL: "/providers/:id",
  BUILTIN_TOOLS: "/builtin-tools",
  MEMORY: "/memory",
  SETUP: "/setup",
  SELECT_TENANT: "/select-tenant",
} as const;
