// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	agentsFieldNames          = builder.RawFieldNames(&Agents{}, true)
	agentsRows                = strings.Join(agentsFieldNames, ",")
	agentsRowsExpectAutoSet   = strings.Join(stringx.Remove(agentsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	agentsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(agentsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	agentsModel interface {
		Insert(ctx context.Context, data *Agents) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Agents, error)
		Update(ctx context.Context, data *Agents) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAgentsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Agents struct {
		Id                  int64          `db:"id"`
		UserId              string         `db:"user_id"`
		AgentId             string         `db:"agent_id"`
		Name                sql.NullString `db:"name"`
		Frontmatter         sql.NullString `db:"frontmatter"` // 专业领域简短描述
		ProviderId          int64          `db:"provider_id"`
		Model               string         `db:"model"`
		ContextWindow       int64          `db:"context_window"`
		MaxToolIterations   int64          `db:"max_tool_iterations"`
		Workspace           string         `db:"workspace"`
		RestrictToWorkspace bool           `db:"restrict_to_workspace"`
		ToolsConfig         string         `db:"tools_config"`      // 工具策略配置
		MemoryConfig        string         `db:"memory_config"`     // 记忆系统配置
		CompactionConfig    string         `db:"compaction_config"` // 上下文压缩配置
		OtherConfig         string         `db:"other_config"`
		Emoji               sql.NullString `db:"emoji"`
		AgentDescription    sql.NullString `db:"agent_description"` // LLM 召唤提示词
		ThinkingLevel       sql.NullString `db:"thinking_level"`
		MaxTokens           int64          `db:"max_tokens"`
		SelfEvolve          bool           `db:"self_evolve"`
		SkillEvolve         bool           `db:"skill_evolve"`
		CreatedAt           time.Time      `db:"created_at"`
		UpdatedAt           time.Time      `db:"updated_at"`
		DeletedAt           sql.NullTime   `db:"deleted_at"`
		IsShared            bool           `db:"is_shared"`
	}
)

func newAgentsModel(conn sqlx.SqlConn) *defaultAgentsModel {
	return &defaultAgentsModel{
		conn:  conn,
		table: `"public"."agents"`,
	}
}

func (m *defaultAgentsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAgentsModel) FindOne(ctx context.Context, id int64) (*Agents, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", agentsRows, m.table)
	var resp Agents
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAgentsModel) Insert(ctx context.Context, data *Agents) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22)", m.table, agentsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.AgentId, data.Name, data.Frontmatter, data.ProviderId, data.Model, data.ContextWindow, data.MaxToolIterations, data.Workspace, data.RestrictToWorkspace, data.ToolsConfig, data.MemoryConfig, data.CompactionConfig, data.OtherConfig, data.Emoji, data.AgentDescription, data.ThinkingLevel, data.MaxTokens, data.SelfEvolve, data.SkillEvolve, data.DeletedAt, data.IsShared)
	return ret, err
}

func (m *defaultAgentsModel) Update(ctx context.Context, data *Agents) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, agentsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.AgentId, data.Name, data.Frontmatter, data.ProviderId, data.Model, data.ContextWindow, data.MaxToolIterations, data.Workspace, data.RestrictToWorkspace, data.ToolsConfig, data.MemoryConfig, data.CompactionConfig, data.OtherConfig, data.Emoji, data.AgentDescription, data.ThinkingLevel, data.MaxTokens, data.SelfEvolve, data.SkillEvolve, data.DeletedAt, data.IsShared)
	return err
}

func (m *defaultAgentsModel) tableName() string {
	return m.table
}
