// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	agentContextFilesFieldNames          = builder.RawFieldNames(&AgentContextFiles{}, true)
	agentContextFilesRows                = strings.Join(agentContextFilesFieldNames, ",")
	agentContextFilesRowsExpectAutoSet   = strings.Join(stringx.Remove(agentContextFilesFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	agentContextFilesRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(agentContextFilesFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	agentContextFilesModel interface {
		Insert(ctx context.Context, data *AgentContextFiles) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AgentContextFiles, error)
		FindOneByAgentIdFileName(ctx context.Context, agentId string, fileName string) (*AgentContextFiles, error)
		Update(ctx context.Context, data *AgentContextFiles) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAgentContextFilesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AgentContextFiles struct {
		Id        int64     `db:"id"`
		UserId    string    `db:"user_id"`
		AgentId   string    `db:"agent_id"`
		FileType  int64     `db:"file_type"`
		FileName  string    `db:"file_name"`
		Content   string    `db:"content"`
		CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newAgentContextFilesModel(conn sqlx.SqlConn) *defaultAgentContextFilesModel {
	return &defaultAgentContextFilesModel{
		conn:  conn,
		table: `"public"."agent_context_files"`,
	}
}

func (m *defaultAgentContextFilesModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAgentContextFilesModel) FindOne(ctx context.Context, id int64) (*AgentContextFiles, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", agentContextFilesRows, m.table)
	var resp AgentContextFiles
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAgentContextFilesModel) FindOneByAgentIdFileName(ctx context.Context, agentId string, fileName string) (*AgentContextFiles, error) {
	var resp AgentContextFiles
	query := fmt.Sprintf("select %s from %s where agent_id = $1 and file_name = $2 limit 1", agentContextFilesRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, agentId, fileName)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAgentContextFilesModel) Insert(ctx context.Context, data *AgentContextFiles) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5)", m.table, agentContextFilesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.AgentId, data.FileType, data.FileName, data.Content)
	return ret, err
}

func (m *defaultAgentContextFilesModel) Update(ctx context.Context, newData *AgentContextFiles) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, agentContextFilesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.UserId, newData.AgentId, newData.FileType, newData.FileName, newData.Content)
	return err
}

func (m *defaultAgentContextFilesModel) tableName() string {
	return m.table
}
