// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	dailyNotesFieldNames          = builder.RawFieldNames(&DailyNotes{}, true)
	dailyNotesRows                = strings.Join(dailyNotesFieldNames, ",")
	dailyNotesRowsExpectAutoSet   = strings.Join(stringx.Remove(dailyNotesFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	dailyNotesRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(dailyNotesFieldNames, "note_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	dailyNotesModel interface {
		Insert(ctx context.Context, data *DailyNotes) (sql.Result, error)
		FindOne(ctx context.Context, noteId string) (*DailyNotes, error)
		Update(ctx context.Context, data *DailyNotes) error
		Delete(ctx context.Context, noteId string) error
	}

	defaultDailyNotesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	DailyNotes struct {
		NoteId    string         `db:"note_id"`
		AgentId   string         `db:"agent_id"`
		NoteDate  time.Time      `db:"note_date"`
		Content   sql.NullString `db:"content"`
		Embedding sql.NullString `db:"embedding"`
		CreatedAt time.Time      `db:"created_at"`
		UpdatedAt time.Time      `db:"updated_at"`
	}
)

func newDailyNotesModel(conn sqlx.SqlConn) *defaultDailyNotesModel {
	return &defaultDailyNotesModel{
		conn:  conn,
		table: `"public"."daily_notes"`,
	}
}

func (m *defaultDailyNotesModel) Delete(ctx context.Context, noteId string) error {
	query := fmt.Sprintf("delete from %s where note_id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, noteId)
	return err
}

func (m *defaultDailyNotesModel) FindOne(ctx context.Context, noteId string) (*DailyNotes, error) {
	query := fmt.Sprintf("select %s from %s where note_id = $1 limit 1", dailyNotesRows, m.table)
	var resp DailyNotes
	err := m.conn.QueryRowCtx(ctx, &resp, query, noteId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDailyNotesModel) Insert(ctx context.Context, data *DailyNotes) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5)", m.table, dailyNotesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.NoteId, data.AgentId, data.NoteDate, data.Content, data.Embedding)
	return ret, err
}

func (m *defaultDailyNotesModel) Update(ctx context.Context, data *DailyNotes) error {
	query := fmt.Sprintf("update %s set %s where note_id = $1", m.table, dailyNotesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.NoteId, data.AgentId, data.NoteDate, data.Content, data.Embedding)
	return err
}

func (m *defaultDailyNotesModel) tableName() string {
	return m.table
}
