// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	mcpServersFieldNames          = builder.RawFieldNames(&McpServers{}, true)
	mcpServersRows                = strings.Join(mcpServersFieldNames, ",")
	mcpServersRowsExpectAutoSet   = strings.Join(stringx.Remove(mcpServersFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	mcpServersRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(mcpServersFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	mcpServersModel interface {
		Insert(ctx context.Context, data *McpServers) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*McpServers, error)
		FindOneByName(ctx context.Context, name string) (*McpServers, error)
		Update(ctx context.Context, data *McpServers) error
		Delete(ctx context.Context, id int64) error
	}

	defaultMcpServersModel struct {
		conn  sqlx.SqlConn
		table string
	}

	McpServers struct {
		Id          int64          `db:"id"`
		UserId      string         `db:"user_id"`
		Name        string         `db:"name"`
		Description sql.NullString `db:"description"`
		Transport   string         `db:"transport"`
		Command     sql.NullString `db:"command"`
		Args        string         `db:"args"`
		Url         sql.NullString `db:"url"`
		Headers     string         `db:"headers"`
		Env         string         `db:"env"`
		ApiKey      sql.NullString `db:"api_key"`
		ToolPrefix  sql.NullString `db:"tool_prefix"`
		TimeoutSec  int64          `db:"timeout_sec"`
		Settings    string         `db:"settings"`
		Enabled     bool           `db:"enabled"`
		CreatedAt   time.Time      `db:"created_at"`
		UpdatedAt   time.Time      `db:"updated_at"`
		IsShared    bool           `db:"is_shared"` // 用户分享标记：true = 其他用户可见此 MCP server
	}
)

func newMcpServersModel(conn sqlx.SqlConn) *defaultMcpServersModel {
	return &defaultMcpServersModel{
		conn:  conn,
		table: `"public"."mcp_servers"`,
	}
}

func (m *defaultMcpServersModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultMcpServersModel) FindOne(ctx context.Context, id int64) (*McpServers, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", mcpServersRows, m.table)
	var resp McpServers
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMcpServersModel) FindOneByName(ctx context.Context, name string) (*McpServers, error) {
	var resp McpServers
	query := fmt.Sprintf("select %s from %s where name = $1 limit 1", mcpServersRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, name)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMcpServersModel) Insert(ctx context.Context, data *McpServers) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)", m.table, mcpServersRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Name, data.Description, data.Transport, data.Command, data.Args, data.Url, data.Headers, data.Env, data.ApiKey, data.ToolPrefix, data.TimeoutSec, data.Settings, data.Enabled, data.IsShared)
	return ret, err
}

func (m *defaultMcpServersModel) Update(ctx context.Context, newData *McpServers) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, mcpServersRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.UserId, newData.Name, newData.Description, newData.Transport, newData.Command, newData.Args, newData.Url, newData.Headers, newData.Env, newData.ApiKey, newData.ToolPrefix, newData.TimeoutSec, newData.Settings, newData.Enabled, newData.IsShared)
	return err
}

func (m *defaultMcpServersModel) tableName() string {
	return m.table
}
