// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	memoriesFieldNames          = builder.RawFieldNames(&Memories{}, true)
	memoriesRows                = strings.Join(memoriesFieldNames, ",")
	memoriesRowsExpectAutoSet   = strings.Join(stringx.Remove(memoriesFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	memoriesRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(memoriesFieldNames, "memory_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	memoriesModel interface {
		Insert(ctx context.Context, data *Memories) (sql.Result, error)
		FindOne(ctx context.Context, memoryId string) (*Memories, error)
		Update(ctx context.Context, data *Memories) error
		Delete(ctx context.Context, memoryId string) error
	}

	defaultMemoriesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Memories struct {
		MemoryId    string         `db:"memory_id"`
		AgentId     string         `db:"agent_id"`
		Content     sql.NullString `db:"content"`
		Embedding   sql.NullString `db:"embedding"`
		Importance  float64        `db:"importance"`
		Category    sql.NullString `db:"category"`
		AccessCount int64          `db:"access_count"`
		CreatedAt   time.Time      `db:"created_at"`
		AccessedAt  sql.NullTime   `db:"accessed_at"`
		UpdatedAt   time.Time      `db:"updated_at"`
	}
)

func newMemoriesModel(conn sqlx.SqlConn) *defaultMemoriesModel {
	return &defaultMemoriesModel{
		conn:  conn,
		table: `"public"."memories"`,
	}
}

func (m *defaultMemoriesModel) Delete(ctx context.Context, memoryId string) error {
	query := fmt.Sprintf("delete from %s where memory_id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, memoryId)
	return err
}

func (m *defaultMemoriesModel) FindOne(ctx context.Context, memoryId string) (*Memories, error) {
	query := fmt.Sprintf("select %s from %s where memory_id = $1 limit 1", memoriesRows, m.table)
	var resp Memories
	err := m.conn.QueryRowCtx(ctx, &resp, query, memoryId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMemoriesModel) Insert(ctx context.Context, data *Memories) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8)", m.table, memoriesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.MemoryId, data.AgentId, data.Content, data.Embedding, data.Importance, data.Category, data.AccessCount, data.AccessedAt)
	return ret, err
}

func (m *defaultMemoriesModel) Update(ctx context.Context, data *Memories) error {
	query := fmt.Sprintf("update %s set %s where memory_id = $1", m.table, memoriesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.MemoryId, data.AgentId, data.Content, data.Embedding, data.Importance, data.Category, data.AccessCount, data.AccessedAt)
	return err
}

func (m *defaultMemoriesModel) tableName() string {
	return m.table
}
