// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	memoryChunksFieldNames          = builder.RawFieldNames(&MemoryChunks{}, true)
	memoryChunksRows                = strings.Join(memoryChunksFieldNames, ",")
	memoryChunksRowsExpectAutoSet   = strings.Join(stringx.Remove(memoryChunksFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	memoryChunksRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(memoryChunksFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	memoryChunksModel interface {
		Insert(ctx context.Context, data *MemoryChunks) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*MemoryChunks, error)
		Update(ctx context.Context, data *MemoryChunks) error
		Delete(ctx context.Context, id int64) error
	}

	defaultMemoryChunksModel struct {
		conn  sqlx.SqlConn
		table string
	}

	MemoryChunks struct {
		Id          int64          `db:"id"`
		DocumentId  sql.NullString `db:"document_id"`
		AgentId     string         `db:"agent_id"`
		UserId      string         `db:"user_id"`
		Path        string         `db:"path"`
		StartLine   int64          `db:"start_line"`
		EndLine     int64          `db:"end_line"`
		Hash        string         `db:"hash"`
		Text        string         `db:"text"`
		Embedding   sql.NullString `db:"embedding"`
		Tsv         sql.NullString `db:"tsv"`
		CustomScope sql.NullString `db:"custom_scope"`
		CreatedAt   time.Time      `db:"created_at"`
		UpdatedAt   time.Time      `db:"updated_at"`
	}
)

func newMemoryChunksModel(conn sqlx.SqlConn) *defaultMemoryChunksModel {
	return &defaultMemoryChunksModel{
		conn:  conn,
		table: `"public"."memory_chunks"`,
	}
}

func (m *defaultMemoryChunksModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultMemoryChunksModel) FindOne(ctx context.Context, id int64) (*MemoryChunks, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", memoryChunksRows, m.table)
	var resp MemoryChunks
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMemoryChunksModel) Insert(ctx context.Context, data *MemoryChunks) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)", m.table, memoryChunksRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.DocumentId, data.AgentId, data.UserId, data.Path, data.StartLine, data.EndLine, data.Hash, data.Text, data.Embedding, data.Tsv, data.CustomScope)
	return ret, err
}

func (m *defaultMemoryChunksModel) Update(ctx context.Context, data *MemoryChunks) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, memoryChunksRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.DocumentId, data.AgentId, data.UserId, data.Path, data.StartLine, data.EndLine, data.Hash, data.Text, data.Embedding, data.Tsv, data.CustomScope)
	return err
}

func (m *defaultMemoryChunksModel) tableName() string {
	return m.table
}
