// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	memoryDocumentsFieldNames          = builder.RawFieldNames(&MemoryDocuments{}, true)
	memoryDocumentsRows                = strings.Join(memoryDocumentsFieldNames, ",")
	memoryDocumentsRowsExpectAutoSet   = strings.Join(stringx.Remove(memoryDocumentsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	memoryDocumentsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(memoryDocumentsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	memoryDocumentsModel interface {
		Insert(ctx context.Context, data *MemoryDocuments) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*MemoryDocuments, error)
		FindOneByAgentIdPath(ctx context.Context, agentId string, path string) (*MemoryDocuments, error)
		Update(ctx context.Context, data *MemoryDocuments) error
		Delete(ctx context.Context, id int64) error
	}

	defaultMemoryDocumentsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	MemoryDocuments struct {
		Id          int64          `db:"id"`
		AgentId     string         `db:"agent_id"`
		UserId      string         `db:"user_id"`
		Path        string         `db:"path"`
		Content     string         `db:"content"`
		Hash        string         `db:"hash"`
		CustomScope sql.NullString `db:"custom_scope"`
		CreatedAt   time.Time      `db:"created_at"`
		UpdatedAt   time.Time      `db:"updated_at"`
	}
)

func newMemoryDocumentsModel(conn sqlx.SqlConn) *defaultMemoryDocumentsModel {
	return &defaultMemoryDocumentsModel{
		conn:  conn,
		table: `"public"."memory_documents"`,
	}
}

func (m *defaultMemoryDocumentsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultMemoryDocumentsModel) FindOne(ctx context.Context, id int64) (*MemoryDocuments, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", memoryDocumentsRows, m.table)
	var resp MemoryDocuments
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMemoryDocumentsModel) FindOneByAgentIdPath(ctx context.Context, agentId string, path string) (*MemoryDocuments, error) {
	var resp MemoryDocuments
	query := fmt.Sprintf("select %s from %s where agent_id = $1 and path = $2 limit 1", memoryDocumentsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, agentId, path)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMemoryDocumentsModel) Insert(ctx context.Context, data *MemoryDocuments) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6)", m.table, memoryDocumentsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.AgentId, data.UserId, data.Path, data.Content, data.Hash, data.CustomScope)
	return ret, err
}

func (m *defaultMemoryDocumentsModel) Update(ctx context.Context, newData *MemoryDocuments) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, memoryDocumentsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.AgentId, newData.UserId, newData.Path, newData.Content, newData.Hash, newData.CustomScope)
	return err
}

func (m *defaultMemoryDocumentsModel) tableName() string {
	return m.table
}
