// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	metaFieldNames          = builder.RawFieldNames(&Meta{}, true)
	metaRows                = strings.Join(metaFieldNames, ",")
	metaRowsExpectAutoSet   = strings.Join(stringx.Remove(metaFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	metaRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(metaFieldNames, "meta_key", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	metaModel interface {
		Insert(ctx context.Context, data *Meta) (sql.Result, error)
		FindOne(ctx context.Context, metaKey string) (*Meta, error)
		Update(ctx context.Context, data *Meta) error
		Delete(ctx context.Context, metaKey string) error
	}

	defaultMetaModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Meta struct {
		MetaKey   string         `db:"meta_key"`
		MetaValue sql.NullString `db:"meta_value"`
		UpdatedAt time.Time      `db:"updated_at"`
	}
)

func newMetaModel(conn sqlx.SqlConn) *defaultMetaModel {
	return &defaultMetaModel{
		conn:  conn,
		table: `"public"."meta"`,
	}
}

func (m *defaultMetaModel) Delete(ctx context.Context, metaKey string) error {
	query := fmt.Sprintf("delete from %s where meta_key = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, metaKey)
	return err
}

func (m *defaultMetaModel) FindOne(ctx context.Context, metaKey string) (*Meta, error) {
	query := fmt.Sprintf("select %s from %s where meta_key = $1 limit 1", metaRows, m.table)
	var resp Meta
	err := m.conn.QueryRowCtx(ctx, &resp, query, metaKey)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMetaModel) Insert(ctx context.Context, data *Meta) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2)", m.table, metaRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.MetaKey, data.MetaValue)
	return ret, err
}

func (m *defaultMetaModel) Update(ctx context.Context, data *Meta) error {
	query := fmt.Sprintf("update %s set %s where meta_key = $1", m.table, metaRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.MetaKey, data.MetaValue)
	return err
}

func (m *defaultMetaModel) tableName() string {
	return m.table
}
