// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	promptsFieldNames          = builder.RawFieldNames(&Prompts{}, true)
	promptsRows                = strings.Join(promptsFieldNames, ",")
	promptsRowsExpectAutoSet   = strings.Join(stringx.Remove(promptsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	promptsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(promptsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	promptsModel interface {
		Insert(ctx context.Context, data *Prompts) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Prompts, error)
		FindOneByPromptNameAgentId(ctx context.Context, promptName string, agentId string) (*Prompts, error)
		Update(ctx context.Context, data *Prompts) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPromptsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Prompts struct {
		Id         int64          `db:"id"`
		PromptName string         `db:"prompt_name"`
		AgentId    string         `db:"agent_id"`
		Content    sql.NullString `db:"content"`
		UpdatedAt  time.Time      `db:"updated_at"`
	}
)

func newPromptsModel(conn sqlx.SqlConn) *defaultPromptsModel {
	return &defaultPromptsModel{
		conn:  conn,
		table: `"public"."prompts"`,
	}
}

func (m *defaultPromptsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultPromptsModel) FindOne(ctx context.Context, id int64) (*Prompts, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", promptsRows, m.table)
	var resp Prompts
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPromptsModel) FindOneByPromptNameAgentId(ctx context.Context, promptName string, agentId string) (*Prompts, error) {
	var resp Prompts
	query := fmt.Sprintf("select %s from %s where prompt_name = $1 and agent_id = $2 limit 1", promptsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, promptName, agentId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPromptsModel) Insert(ctx context.Context, data *Prompts) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3)", m.table, promptsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.PromptName, data.AgentId, data.Content)
	return ret, err
}

func (m *defaultPromptsModel) Update(ctx context.Context, newData *Prompts) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, promptsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.PromptName, newData.AgentId, newData.Content)
	return err
}

func (m *defaultPromptsModel) tableName() string {
	return m.table
}
