// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	providersFieldNames          = builder.RawFieldNames(&Providers{}, true)
	providersRows                = strings.Join(providersFieldNames, ",")
	providersRowsExpectAutoSet   = strings.Join(stringx.Remove(providersFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	providersRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(providersFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	providersModel interface {
		Insert(ctx context.Context, data *Providers) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*Providers, error)
		FindOneByUserIdName(ctx context.Context, userId string, name string) (*Providers, error)
		Update(ctx context.Context, data *Providers) error
		Delete(ctx context.Context, id string) error
	}

	defaultProvidersModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Providers struct {
		Id           string         `db:"id"`
		UserId       string         `db:"user_id"`
		Name         string         `db:"name"`
		ProviderType string         `db:"provider_type"`
		ApiBase      sql.NullString `db:"api_base"`
		ApiKey       string         `db:"api_key"`
		DisplayName  sql.NullString `db:"display_name"`
		Enabled      bool           `db:"enabled"`
		Settings     string         `db:"settings"`
		CreatedAt    time.Time      `db:"created_at"`
		UpdatedAt    time.Time      `db:"updated_at"`
	}
)

func newProvidersModel(conn sqlx.SqlConn) *defaultProvidersModel {
	return &defaultProvidersModel{
		conn:  conn,
		table: `"public"."providers"`,
	}
}

func (m *defaultProvidersModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultProvidersModel) FindOne(ctx context.Context, id string) (*Providers, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", providersRows, m.table)
	var resp Providers
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProvidersModel) FindOneByUserIdName(ctx context.Context, userId string, name string) (*Providers, error) {
	var resp Providers
	query := fmt.Sprintf("select %s from %s where user_id = $1 and name = $2 limit 1", providersRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, name)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProvidersModel) Insert(ctx context.Context, data *Providers) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9)", m.table, providersRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.Name, data.ProviderType, data.ApiBase, data.ApiKey, data.DisplayName, data.Enabled, data.Settings)
	return ret, err
}

func (m *defaultProvidersModel) Update(ctx context.Context, newData *Providers) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, providersRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.UserId, newData.Name, newData.ProviderType, newData.ApiBase, newData.ApiKey, newData.DisplayName, newData.Enabled, newData.Settings)
	return err
}

func (m *defaultProvidersModel) tableName() string {
	return m.table
}
