// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sessionsFieldNames          = builder.RawFieldNames(&Sessions{}, true)
	sessionsRows                = strings.Join(sessionsFieldNames, ",")
	sessionsRowsExpectAutoSet   = strings.Join(stringx.Remove(sessionsFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	sessionsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(sessionsFieldNames, "session_key", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	sessionsModel interface {
		Insert(ctx context.Context, data *Sessions) (sql.Result, error)
		FindOne(ctx context.Context, sessionKey string) (*Sessions, error)
		Update(ctx context.Context, data *Sessions) error
		Delete(ctx context.Context, sessionKey string) error
	}

	defaultSessionsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Sessions struct {
		SessionKey    string         `db:"session_key"`
		AgentId       string         `db:"agent_id"`
		Messages      sql.NullString `db:"messages"`
		Summary       sql.NullString `db:"summary"`
		Label         sql.NullString `db:"label"`
		MessagesCount int64          `db:"messages_count"`
		InputTokens   int64          `db:"input_tokens"`
		OutputTokens  int64          `db:"output_tokens"`
		CreatedAt     time.Time      `db:"created_at"`
		UpdatedAt     time.Time      `db:"updated_at"`
	}
)

func newSessionsModel(conn sqlx.SqlConn) *defaultSessionsModel {
	return &defaultSessionsModel{
		conn:  conn,
		table: `"public"."sessions"`,
	}
}

func (m *defaultSessionsModel) Delete(ctx context.Context, sessionKey string) error {
	query := fmt.Sprintf("delete from %s where session_key = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, sessionKey)
	return err
}

func (m *defaultSessionsModel) FindOne(ctx context.Context, sessionKey string) (*Sessions, error) {
	query := fmt.Sprintf("select %s from %s where session_key = $1 limit 1", sessionsRows, m.table)
	var resp Sessions
	err := m.conn.QueryRowCtx(ctx, &resp, query, sessionKey)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSessionsModel) Insert(ctx context.Context, data *Sessions) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8)", m.table, sessionsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.SessionKey, data.AgentId, data.Messages, data.Summary, data.Label, data.MessagesCount, data.InputTokens, data.OutputTokens)
	return ret, err
}

func (m *defaultSessionsModel) Update(ctx context.Context, data *Sessions) error {
	query := fmt.Sprintf("update %s set %s where session_key = $1", m.table, sessionsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.SessionKey, data.AgentId, data.Messages, data.Summary, data.Label, data.MessagesCount, data.InputTokens, data.OutputTokens)
	return err
}

func (m *defaultSessionsModel) tableName() string {
	return m.table
}
