// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	skillGrantsFieldNames          = builder.RawFieldNames(&SkillGrants{}, true)
	skillGrantsRows                = strings.Join(skillGrantsFieldNames, ",")
	skillGrantsRowsExpectAutoSet   = strings.Join(stringx.Remove(skillGrantsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	skillGrantsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(skillGrantsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	skillGrantsModel interface {
		Insert(ctx context.Context, data *SkillGrants) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SkillGrants, error)
		FindOneBySkillIdAgentId(ctx context.Context, skillId string, agentId string) (*SkillGrants, error)
		Update(ctx context.Context, data *SkillGrants) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSkillGrantsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SkillGrants struct {
		Id        int64     `db:"id"`
		SkillId   string    `db:"skill_id"`
		AgentId   string    `db:"agent_id"`
		Version   int64     `db:"version"`
		CreatedAt time.Time `db:"created_at"`
	}
)

func newSkillGrantsModel(conn sqlx.SqlConn) *defaultSkillGrantsModel {
	return &defaultSkillGrantsModel{
		conn:  conn,
		table: `"public"."skill_grants"`,
	}
}

func (m *defaultSkillGrantsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSkillGrantsModel) FindOne(ctx context.Context, id int64) (*SkillGrants, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", skillGrantsRows, m.table)
	var resp SkillGrants
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSkillGrantsModel) FindOneBySkillIdAgentId(ctx context.Context, skillId string, agentId string) (*SkillGrants, error) {
	var resp SkillGrants
	query := fmt.Sprintf("select %s from %s where skill_id = $1 and agent_id = $2 limit 1", skillGrantsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, skillId, agentId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSkillGrantsModel) Insert(ctx context.Context, data *SkillGrants) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3)", m.table, skillGrantsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.SkillId, data.AgentId, data.Version)
	return ret, err
}

func (m *defaultSkillGrantsModel) Update(ctx context.Context, newData *SkillGrants) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, skillGrantsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.SkillId, newData.AgentId, newData.Version)
	return err
}

func (m *defaultSkillGrantsModel) tableName() string {
	return m.table
}
