// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	skillsFieldNames          = builder.RawFieldNames(&Skills{}, true)
	skillsRows                = strings.Join(skillsFieldNames, ",")
	skillsRowsExpectAutoSet   = strings.Join(stringx.Remove(skillsFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	skillsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(skillsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	skillsModel interface {
		Insert(ctx context.Context, data *Skills) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*Skills, error)
		FindOneByUserIdSlug(ctx context.Context, userId string, slug string) (*Skills, error)
		Update(ctx context.Context, data *Skills) error
		Delete(ctx context.Context, id string) error
	}

	defaultSkillsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Skills struct {
		Id          string         `db:"id"`
		UserId      string         `db:"user_id"`
		Name        string         `db:"name"`
		Slug        string         `db:"slug"`
		Description sql.NullString `db:"description"`
		Enabled     bool           `db:"enabled"`
		Status      string         `db:"status"`
		Version     int64          `db:"version"`
		CreatedAt   time.Time      `db:"created_at"`
		UpdatedAt   time.Time      `db:"updated_at"`
	}
)

func newSkillsModel(conn sqlx.SqlConn) *defaultSkillsModel {
	return &defaultSkillsModel{
		conn:  conn,
		table: `"public"."skills"`,
	}
}

func (m *defaultSkillsModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSkillsModel) FindOne(ctx context.Context, id string) (*Skills, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", skillsRows, m.table)
	var resp Skills
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSkillsModel) FindOneByUserIdSlug(ctx context.Context, userId string, slug string) (*Skills, error) {
	var resp Skills
	query := fmt.Sprintf("select %s from %s where user_id = $1 and slug = $2 limit 1", skillsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, slug)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSkillsModel) Insert(ctx context.Context, data *Skills) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8)", m.table, skillsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.Name, data.Slug, data.Description, data.Enabled, data.Status, data.Version)
	return ret, err
}

func (m *defaultSkillsModel) Update(ctx context.Context, newData *Skills) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, skillsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.UserId, newData.Name, newData.Slug, newData.Description, newData.Enabled, newData.Status, newData.Version)
	return err
}

func (m *defaultSkillsModel) tableName() string {
	return m.table
}
