// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	spansFieldNames          = builder.RawFieldNames(&Spans{}, true)
	spansRows                = strings.Join(spansFieldNames, ",")
	spansRowsExpectAutoSet   = strings.Join(stringx.Remove(spansFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	spansRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(spansFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	spansModel interface {
		Insert(ctx context.Context, data *Spans) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Spans, error)
		Update(ctx context.Context, data *Spans) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSpansModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Spans struct {
		Id            int64           `db:"id"`
		TraceId       string          `db:"trace_id"`
		ParentSpanId  sql.NullString  `db:"parent_span_id"`
		AgentId       sql.NullString  `db:"agent_id"`
		SpanType      string          `db:"span_type"`
		Name          sql.NullString  `db:"name"`
		StartTime     time.Time       `db:"start_time"`
		EndTime       sql.NullTime    `db:"end_time"`
		DurationMs    sql.NullInt64   `db:"duration_ms"`
		Status        string          `db:"status"`
		Error         sql.NullString  `db:"error"`
		Level         string          `db:"level"`
		Model         sql.NullString  `db:"model"`
		Provider      sql.NullString  `db:"provider"`
		InputTokens   sql.NullInt64   `db:"input_tokens"`
		OutputTokens  sql.NullInt64   `db:"output_tokens"`
		TotalCost     sql.NullFloat64 `db:"total_cost"`
		FinishReason  sql.NullString  `db:"finish_reason"`
		ModelParams   sql.NullString  `db:"model_params"`
		ToolName      sql.NullString  `db:"tool_name"`
		ToolCallId    sql.NullString  `db:"tool_call_id"`
		InputPreview  sql.NullString  `db:"input_preview"`
		OutputPreview sql.NullString  `db:"output_preview"`
		Metadata      sql.NullString  `db:"metadata"`
		CreatedAt     time.Time       `db:"created_at"`
	}
)

func newSpansModel(conn sqlx.SqlConn) *defaultSpansModel {
	return &defaultSpansModel{
		conn:  conn,
		table: `"public"."spans"`,
	}
}

func (m *defaultSpansModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSpansModel) FindOne(ctx context.Context, id int64) (*Spans, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", spansRows, m.table)
	var resp Spans
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSpansModel) Insert(ctx context.Context, data *Spans) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23)", m.table, spansRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TraceId, data.ParentSpanId, data.AgentId, data.SpanType, data.Name, data.StartTime, data.EndTime, data.DurationMs, data.Status, data.Error, data.Level, data.Model, data.Provider, data.InputTokens, data.OutputTokens, data.TotalCost, data.FinishReason, data.ModelParams, data.ToolName, data.ToolCallId, data.InputPreview, data.OutputPreview, data.Metadata)
	return ret, err
}

func (m *defaultSpansModel) Update(ctx context.Context, data *Spans) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, spansRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.TraceId, data.ParentSpanId, data.AgentId, data.SpanType, data.Name, data.StartTime, data.EndTime, data.DurationMs, data.Status, data.Error, data.Level, data.Model, data.Provider, data.InputTokens, data.OutputTokens, data.TotalCost, data.FinishReason, data.ModelParams, data.ToolName, data.ToolCallId, data.InputPreview, data.OutputPreview, data.Metadata)
	return err
}

func (m *defaultSpansModel) tableName() string {
	return m.table
}
