// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	stateFieldNames          = builder.RawFieldNames(&State{}, true)
	stateRows                = strings.Join(stateFieldNames, ",")
	stateRowsExpectAutoSet   = strings.Join(stringx.Remove(stateFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	stateRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(stateFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	stateModel interface {
		Insert(ctx context.Context, data *State) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*State, error)
		FindOneByStateKeyAgentId(ctx context.Context, stateKey string, agentId string) (*State, error)
		Update(ctx context.Context, data *State) error
		Delete(ctx context.Context, id int64) error
	}

	defaultStateModel struct {
		conn  sqlx.SqlConn
		table string
	}

	State struct {
		Id         int64          `db:"id"`
		StateKey   string         `db:"state_key"`
		AgentId    string         `db:"agent_id"`
		StateValue sql.NullString `db:"state_value"`
		UpdatedAt  time.Time      `db:"updated_at"`
	}
)

func newStateModel(conn sqlx.SqlConn) *defaultStateModel {
	return &defaultStateModel{
		conn:  conn,
		table: `"public"."state"`,
	}
}

func (m *defaultStateModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultStateModel) FindOne(ctx context.Context, id int64) (*State, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", stateRows, m.table)
	var resp State
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultStateModel) FindOneByStateKeyAgentId(ctx context.Context, stateKey string, agentId string) (*State, error) {
	var resp State
	query := fmt.Sprintf("select %s from %s where state_key = $1 and agent_id = $2 limit 1", stateRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, stateKey, agentId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultStateModel) Insert(ctx context.Context, data *State) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3)", m.table, stateRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.StateKey, data.AgentId, data.StateValue)
	return ret, err
}

func (m *defaultStateModel) Update(ctx context.Context, newData *State) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, stateRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.StateKey, newData.AgentId, newData.StateValue)
	return err
}

func (m *defaultStateModel) tableName() string {
	return m.table
}
