// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	toolGrantsFieldNames          = builder.RawFieldNames(&ToolGrants{}, true)
	toolGrantsRows                = strings.Join(toolGrantsFieldNames, ",")
	toolGrantsRowsExpectAutoSet   = strings.Join(stringx.Remove(toolGrantsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	toolGrantsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(toolGrantsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	toolGrantsModel interface {
		Insert(ctx context.Context, data *ToolGrants) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ToolGrants, error)
		Update(ctx context.Context, data *ToolGrants) error
		Delete(ctx context.Context, id int64) error
	}

	defaultToolGrantsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ToolGrants struct {
		Id        int64          `db:"id"`
		UserId    string         `db:"user_id"`
		ToolName  string         `db:"tool_name"`
		Enabled   sql.NullBool   `db:"enabled"`
		Settings  sql.NullString `db:"settings"`
		UpdatedAt time.Time      `db:"updated_at"`
	}
)

func newToolGrantsModel(conn sqlx.SqlConn) *defaultToolGrantsModel {
	return &defaultToolGrantsModel{
		conn:  conn,
		table: `"public"."tool_grants"`,
	}
}

func (m *defaultToolGrantsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultToolGrantsModel) FindOne(ctx context.Context, id int64) (*ToolGrants, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", toolGrantsRows, m.table)
	var resp ToolGrants
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultToolGrantsModel) Insert(ctx context.Context, data *ToolGrants) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4)", m.table, toolGrantsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.ToolName, data.Enabled, data.Settings)
	return ret, err
}

func (m *defaultToolGrantsModel) Update(ctx context.Context, data *ToolGrants) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, toolGrantsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.ToolName, data.Enabled, data.Settings)
	return err
}

func (m *defaultToolGrantsModel) tableName() string {
	return m.table
}
