// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/lib/pq"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tracesFieldNames          = builder.RawFieldNames(&Traces{}, true)
	tracesRows                = strings.Join(tracesFieldNames, ",")
	tracesRowsExpectAutoSet   = strings.Join(stringx.Remove(tracesFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	tracesRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(tracesFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	tracesModel interface {
		Insert(ctx context.Context, data *Traces) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Traces, error)
		Update(ctx context.Context, data *Traces) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTracesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Traces struct {
		Id                int64          `db:"id"`
		ParentTraceId     sql.NullString `db:"parent_trace_id"`
		AgentId           sql.NullString `db:"agent_id"`
		UserId            sql.NullString `db:"user_id"`
		SessionKey        sql.NullString `db:"session_key"`
		RunId             sql.NullString `db:"run_id"`
		StartTime         time.Time      `db:"start_time"`
		EndTime           sql.NullTime   `db:"end_time"`
		DurationMs        sql.NullInt64  `db:"duration_ms"`
		Name              sql.NullString `db:"name"`
		Channel           sql.NullString `db:"channel"`
		InputPreview      sql.NullString `db:"input_preview"`
		OutputPreview     sql.NullString `db:"output_preview"`
		TotalInputTokens  int64          `db:"total_input_tokens"`
		TotalOutputTokens int64          `db:"total_output_tokens"`
		TotalCost         float64        `db:"total_cost"`
		SpanCount         int64          `db:"span_count"`
		LlmCallCount      int64          `db:"llm_call_count"`
		ToolCallCount     int64          `db:"tool_call_count"`
		Status            string         `db:"status"`
		Error             sql.NullString `db:"error"`
		Metadata          sql.NullString `db:"metadata"`
		Tags              pq.StringArray `db:"tags"`
		CreatedAt         time.Time      `db:"created_at"`
	}
)

func newTracesModel(conn sqlx.SqlConn) *defaultTracesModel {
	return &defaultTracesModel{
		conn:  conn,
		table: `"public"."traces"`,
	}
}

func (m *defaultTracesModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTracesModel) FindOne(ctx context.Context, id int64) (*Traces, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", tracesRows, m.table)
	var resp Traces
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTracesModel) Insert(ctx context.Context, data *Traces) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22)", m.table, tracesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ParentTraceId, data.AgentId, data.UserId, data.SessionKey, data.RunId, data.StartTime, data.EndTime, data.DurationMs, data.Name, data.Channel, data.InputPreview, data.OutputPreview, data.TotalInputTokens, data.TotalOutputTokens, data.TotalCost, data.SpanCount, data.LlmCallCount, data.ToolCallCount, data.Status, data.Error, data.Metadata, data.Tags)
	return ret, err
}

func (m *defaultTracesModel) Update(ctx context.Context, data *Traces) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, tracesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.ParentTraceId, data.AgentId, data.UserId, data.SessionKey, data.RunId, data.StartTime, data.EndTime, data.DurationMs, data.Name, data.Channel, data.InputPreview, data.OutputPreview, data.TotalInputTokens, data.TotalOutputTokens, data.TotalCost, data.SpanCount, data.LlmCallCount, data.ToolCallCount, data.Status, data.Error, data.Metadata, data.Tags)
	return err
}

func (m *defaultTracesModel) tableName() string {
	return m.table
}
