// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

export interface Agent {
	// Basic fields
	id: string
	display_name: string
	frontmatter?: string
	owner_id: string
	// LLM configuration
	provider_id: number
	model: string
	context_window: number
	max_tool_iterations: number
	// Workspace
	workspace: string
	restrict_to_workspace: boolean
	// Type and status
	agent_type: string
	is_default: boolean
	status: string
	// JSONB configs//    ToolsConfig []byte `json:"tools_config,omitempty"`//    MemoryConfig []byte `json:"memory_config,omitempty"`//    CompactionConfig []byte `json:"compaction_config,omitempty"`//    OtherConfig []byte `json:"other_config,omitempty"`// V3 fields
	emoji?: string
	agent_description?: string
	thinking_level?: string
	max_tokens?: number
	self_evolve?: boolean
	skill_evolve?: boolean
	is_shared: boolean
	created_by?: string
	created_by_name: string
	// Timestamps
	created_at: number
	updated_at: number
}

export interface AgentAuthorizationMCP {
	server_id: string
	server_name: string
	transport: string
	enabled: boolean
}

export interface AgentAuthorizationSkill {
	id: number
	name: string
	slug: string
	description: string
	version: number
	visibility: string
	is_system: boolean
	created_by?: string
	created_by_name?: string
}

export interface AgentAuthorizationToolPolicy {
	profile?: string
	allow?: Array<string>
	deny?: Array<string>
	alsoAllow?: Array<string>
	toolCallPrefix?: string
}

export interface AuthResp {
	access_token: string
	refresh_token: string
	user_id: string
	username: string
	expires_in: number
	token_type: string
}

export interface BootstrapFile {
	name: string // filename (e.g. "SOUL.md")
	missing: boolean // true if file doesn't exist
	size?: number // file size in bytes
	content?: string // file content (only in get/set responses)
}

export interface BuiltinToolDef {
	name: string
	display?: string
	desc?: string
	enabled: boolean
}

export interface CostSummaryRow {
	agent_id?: string
	total_cost: number
	total_input_tokens: number
	total_output_tokens: number
	trace_count: number
}

export interface CreateAgentReq {
	display_name: string
	frontmatter?: string
	provider_id: number
	model: string
	agent_description?: string
	// Optional advanced fields
	context_window?: number
	max_tool_iterations?: number
	workspace?: string
	//    ToolsConfig []byte `json:"tools_config,optional"`//    MemoryConfig []byte `json:"memory_config,optional"`//    CompactionConfig []byte `json:"compaction_config,optional"`//    OtherConfig []byte `json:"other_config,optional"`// V3 fields
	emoji?: string
	thinking_level?: string
	max_tokens?: number
	self_evolve?: boolean
	skill_evolve?: boolean
	is_shared?: boolean
}

export interface CreateAgentResp {
	agent: Agent
}

export interface CreateMCPServerReq {
	name: string
	description?: string
	transport: string
	command?: string
	args?: string // JSON array string
	url?: string
	headers?: string // JSON object string
	env?: string // JSON object string
	api_key?: string
	tool_prefix?: string
	timeout_sec?: number
	settings?: string // JSON object string
	enabled?: boolean
}

export interface CreateMCPServerResp {
	server: MCPServer
}

export interface CreateProviderReq {
	name: string
	description?: string
	provider_type: string
	api_base: string
	api_key: string
	enabled: boolean
}

export interface CreateProviderResp {
	provider: Provider
}

export interface CreateSessionReq {
	agent_id: string
}

export interface CreateSessionResp {
	session: Session
}

export interface DeleteAgentReq {
}
export interface DeleteAgentReqParams {
}

export interface DeleteAgentResp {
}

export interface DeleteMCPServerReq {
}
export interface DeleteMCPServerReqParams {
}

export interface DeleteMCPServerResp {
}

export interface DeleteMemoryDocumentReq {
}
export interface DeleteMemoryDocumentReqParams {
}

export interface DeleteMemoryDocumentResp {
	status: string
}

export interface DeleteProviderReq {
}
export interface DeleteProviderReqParams {
}

export interface DeleteProviderResp {
}

export interface DeleteSessionReq {
}
export interface DeleteSessionReqParams {
}

export interface DeleteSessionResp {
}

export interface ExportTraceEntry {
	trace: Trace
	spans: Array<Span>
	sub_traces?: Array<ExportTraceEntry>
}

export interface ExportTraceReq {
}
export interface ExportTraceReqParams {
}

export interface ExportTraceResp {
}

export interface GetAgentAuthorizationsReq {
}
export interface GetAgentAuthorizationsReqParams {
}

export interface GetAgentAuthorizationsResp {
	skills: Array<AgentAuthorizationSkill>
	mcp_servers: Array<AgentAuthorizationMCP>
	tool_policy?: AgentAuthorizationToolPolicy
}

export interface GetAgentFileReq {
}
export interface GetAgentFileReqParams {
}

export interface GetAgentFileResp {
	agent_id: string
	file: BootstrapFile
}

export interface GetAgentReq {
}
export interface GetAgentReqParams {
}

export interface GetAgentResp {
	agent: Agent
}

export interface GetBuiltinToolReq {
}
export interface GetBuiltinToolReqParams {
}

export interface GetBuiltinToolResp {
	tool: BuiltinToolDef
}

export interface GetCostSummaryReq {
}
export interface GetCostSummaryReqParams {
	agent_id?: string
	from?: string // RFC3339 timestamp
	to?: string // RFC3339 timestamp
}

export interface GetCostSummaryResp {
	rows: Array<CostSummaryRow>
}

export interface GetMCPServerReq {
}
export interface GetMCPServerReqParams {
}

export interface GetMCPServerResp {
	server: MCPServer
}

export interface GetMeReq {
}

export interface GetMeResp {
	user: UserResp
}

export interface GetMemoryDocumentReq {
}
export interface GetMemoryDocumentReqParams {
}

export interface GetMemoryDocumentResp {
	document: MemoryDocument
}

export interface GetProviderReq {
}
export interface GetProviderReqParams {
}

export interface GetProviderResp {
	provider: Provider
}

export interface GetSessionReq {
}
export interface GetSessionReqParams {
}

export interface GetSessionResp {
	session: Session
}

export interface GetSkillReq {
}
export interface GetSkillReqParams {
}

export interface GetSkillResp {
	skill: SkillResp
	content: string
}

export interface GetSystemHealthReq {
}

export interface GetSystemHealthResp {
	health: SystemHealth
	quota_usage: QuotaUsage
}

export interface GetSystemPromptPreviewReq {
}
export interface GetSystemPromptPreviewReqParams {
	mode?: string // full|task|minimal|none
	user_id?: string
}

export interface GetSystemPromptPreviewResp {
	mode: string
	prompt: string
	token_count: number
	sections: Array<PromptSection>
	tools?: Array<ToolDefinition>
}

export interface GetTraceReq {
}
export interface GetTraceReqParams {
}

export interface GetTraceResp {
	trace: Trace
	spans: Array<Span>
}

export interface GetUsageSummaryReq {
}
export interface GetUsageSummaryReqParams {
	period?: string
	agent_id?: string
	channel?: string
	provider?: string
	model?: string
}

export interface GetUsageSummaryResp {
	current: UsageSummary
	previous: UsageSummary
}

export interface GetUsageTimeSeriesReq {
}
export interface GetUsageTimeSeriesReqParams {
	from: string
	to: string
	group_by?: string
	agent_id?: string
	channel?: string
	provider?: string
	model?: string
}

export interface GetUsageTimeSeriesResp {
	points: Array<UsageTimeSeriesPoint>
}

export interface GrantMCPServerAgentReq {
	agent_id: string
	tool_allow?: string // JSON array string
	tool_deny?: string // JSON array string
}
export interface GrantMCPServerAgentReqParams {
}

export interface GrantMCPServerAgentResp {
	grant: MCPAgentGrant
}

export interface GrantSkillAgentReq {
	agent_id: string
}
export interface GrantSkillAgentReqParams {
}

export interface GrantSkillAgentResp {
	grant: SkillAgentGrant
}

export interface IndexAllReq {
}
export interface IndexAllReqParams {
}

export interface IndexAllResp {
	status: string
	count?: number
	processed?: number
}

export interface IndexDocumentReq {
	path: string
}
export interface IndexDocumentReqParams {
}

export interface IndexDocumentResp {
	status: string
	count?: number
}

export interface ListAgentFilesReq {
}
export interface ListAgentFilesReqParams {
}

export interface ListAgentFilesResp {
	agent_id: string
	files: Array<BootstrapFile>
}

export interface ListAgentMCPServersReq {
}
export interface ListAgentMCPServersReqParams {
}

export interface ListAgentMCPServersResp {
	grants: Array<MCPAgentGrant>
}

export interface ListAgentMemoryDocumentsReq {
}
export interface ListAgentMemoryDocumentsReqParams {
}

export interface ListAgentSkillsReq {
}
export interface ListAgentSkillsReqParams {
}

export interface ListAgentsReq {
}

export interface ListAgentsResp {
	total: number
	agents: Array<Agent>
}

export interface ListBuiltinToolsReq {
}

export interface ListBuiltinToolsResp {
	tools: Array<BuiltinToolDef>
}

export interface ListMCPServerGrantsReq {
}
export interface ListMCPServerGrantsReqParams {
}

export interface ListMCPServerGrantsResp {
	agent_grants: Array<MCPAgentGrant>
}

export interface ListMCPServerToolsReq {
}
export interface ListMCPServerToolsReqParams {
}

export interface ListMCPServerToolsResp {
	tools: Array<MCPToolInfo>
}

export interface ListMCPServersReq {
}

export interface ListMCPServersResp {
	total: number
	servers: Array<MCPServer>
}

export interface ListMemoryChunksReq {
}
export interface ListMemoryChunksReqParams {
	path: string
}

export interface ListMemoryChunksResp {
	chunks: Array<MemoryChunk>
}

export interface ListMemoryDocumentsReq {
}

export interface ListMemoryDocumentsResp {
	documents: Array<MemoryDocument>
}

export interface ListProviderModelsReq {
}
export interface ListProviderModelsReqParams {
}

export interface ListProviderModelsResp {
	models: Array<string>
}

export interface ListProvidersReq {
}

export interface ListProvidersResp {
	total: number
	providers: Array<Provider>
}

export interface ListSessionsReq {
}
export interface ListSessionsReqParams {
	offset?: number
	limit?: number
}

export interface ListSessionsResp {
	total: number
	sessions: Array<Session>
}

export interface ListSkillGrantsReq {
}
export interface ListSkillGrantsReqParams {
}

export interface ListSkillGrantsResp {
	agent_grants: Array<SkillAgentGrant>
}

export interface ListSkillsReq {
}

export interface ListTracesReq {
}
export interface ListTracesReqParams {
	agent_id?: string
	user_id?: string
	session_key?: string
	status?: string
	channel?: string
	limit?: number // max 200
	offset?: number
}

export interface ListTracesResp {
	traces: Array<Trace>
	total: number
	limit: number
	offset: number
}

export interface LoginReq {
	username: string
	password: string
}

export interface LogoutReq {
}

export interface LogoutResp {
}

export interface MCPAgentGrant {
	id: string
	server_id: string
	agent_id: string
	agent_name?: string // display name, enriched
	enabled: boolean
	tool_allow?: string // JSON array string of allowed tool names
	tool_deny?: string // JSON array string of denied tool names
	granted_by?: string
	created_at: number
}

export interface MCPServer {
	id: string
	name: string
	description?: string
	transport: string // "stdio", "sse", "streamable-http"
	command?: string
	args?: string // JSON array string
	url?: string
	headers?: string // JSON object string
	env?: string // JSON object string
	api_key?: string
	tool_prefix?: string
	timeout_sec: number
	settings?: string // JSON object string
	enabled: boolean
	is_shared: boolean
	created_by?: string
	created_by_name: string // display name, enriched in responses
	agent_count?: number // enriched in list response
	created_at: number
	updated_at: number
}

export interface MCPToolInfo {
	name: string
	description?: string
}

export interface MemoryChunk {
	id?: string
	start_line: number
	end_line: number
	text_preview: string
	has_embedding: boolean
}

export interface MemoryDocument {
	document_id: number
	path: string
	content: string
	agent_id?: string
	updated_at?: number
	created_at?: number
}

export interface PromptSection {
	name: string // section name from markdown header
	start: number // character position start
	end: number // character position end
}

export interface Provider {
	id: number
	name: string
	description?: string
	provider_type: string
	api_base: string
	api_key: string
	enabled: boolean
	is_shared: boolean
	created_by?: string
	created_by_name: string
}

export interface PutMemoryDocumentReq {
	content: string
}
export interface PutMemoryDocumentReqParams {
}

export interface PutMemoryDocumentResp {
	document: MemoryDocument
}

export interface QuotaUsage {
	requests_today: number
	input_tokens_today: number
	output_tokens_today: number
	cost_today: number
}

export interface ReconnectMCPServerReq {
}
export interface ReconnectMCPServerReqParams {
}

export interface ReconnectMCPServerResp {
}

export interface RefreshReq {
	refresh_token: string
}

export interface RegisterReq {
	email: string
	password: string
	username: string
}

export interface RevokeMCPServerAgentGrantReq {
}
export interface RevokeMCPServerAgentGrantReqParams {
}

export interface RevokeMCPServerAgentGrantResp {
}

export interface RevokeSkillAgentGrantReq {
}
export interface RevokeSkillAgentGrantReqParams {
}

export interface RevokeSkillAgentGrantResp {
}

export interface SearchMemoryReq {
	query: string
	limit?: number
	offset?: number
}
export interface SearchMemoryReqParams {
}

export interface SearchMemoryResp {
	results: Array<SearchResult>
	total?: number
}

export interface SearchResult {
	path: string
	content: string
	score?: number
	highlights?: string
}

export interface Session {
	id: number
	agent_id: string
	title: string
	preview: string
	message_count: number
	created: string
	updated: string
}

export interface SetAgentFileReq {
	content: string
	propagate?: boolean // push change to all existing user instances
}
export interface SetAgentFileReqParams {
}

export interface SetAgentFileResp {
	agent_id: string
	file: BootstrapFile
	propagated: number // number of instances where file was propagated
}

export interface SkillAgentGrant {
	id: string
	skill_id: number
	agent_id: string
	agent_name?: string
	enabled: boolean
	granted_by?: string
	created_at: number
}

export interface SkillResp {
	id: number
	name: string
	slug: string
	description: string
	enabled: boolean
	status: string
	version: number
	is_system: boolean
	source: string
	visibility: string
	tags: Array<string>
	missing_deps: Array<string>
	content_url?: string
	is_shared: boolean
	created_by?: string
	created_by_name: string
	agent_count?: number
}

export interface SkillWithGrantResp {
	id: number
	name: string
	slug: string
	description: string
	enabled: boolean
	status: string
	version: number
	is_system: boolean
	source: string
	visibility: string
	tags: Array<string>
	missing_deps: Array<string>
	granted: boolean
	is_shared: boolean
	created_by?: string
	created_by_name: string
	agent_count?: number
}

export interface SkillsResp {
	skills: Array<SkillResp>
}

export interface SkillsWithGrantResp {
	skills: Array<SkillWithGrantResp>
}

export interface Span {
	id: string
	trace_id: string
	parent_span_id?: string
	agent_id?: string
	span_type: string
	name?: string
	start_time: number
	end_time?: number
	duration_ms?: number
	status: string
	error?: string
	level?: string
	model?: string
	provider?: string
	input_tokens?: number
	output_tokens?: number
	total_cost?: number
	finish_reason?: string
	tool_name?: string
	tool_call_id?: string
	input_preview?: string
	output_preview?: string
	metadata?: string
	created_at: number
}

export interface SystemHealth {
	version: string
	uptime: number
	agents: number
	tools: number
	sessions: number
	providers: number
	skills: number
	memory: number
	document: number
	channelTotal: number
	channelOnline: number
	channelDegraded: number
	channelFailed: number
}

export interface TestMCPServerConnectionReq {
	name: string
	transport: string
	command?: string
	args?: string // JSON array string
	url?: string
	headers?: string // JSON object string
	env?: string // JSON object string
	api_key?: string
	timeout_sec?: number
}

export interface TestMCPServerConnectionResp {
	success: boolean
	tool_count?: number
	error?: string
}

export interface ToggleSkillGrantResp {
	enabled: boolean
}

export interface ToolDefinition {
	name: string
	description?: string
}

export interface Trace {
	id: string
	parent_trace_id?: string
	agent_id?: string
	user_id?: string
	session_id?: number
	run_id?: string
	start_time: number
	end_time?: number
	duration_ms?: number
	name?: string
	channel?: string
	input_preview?: string
	output_preview?: string
	total_input_tokens: number
	total_output_tokens: number
	total_cost: number
	span_count: number
	llm_call_count: number
	tool_call_count: number
	status: string
	error?: string
	metadata?: string
	tags?: string
	team_id?: string
	created_at: number
}

export interface UpdateAgentReq {
	// All fields are optional for partial updates
	display_name?: string
	frontmatter?: string
	provider_id?: number
	model?: string
	status?: string
	context_window?: number
	max_tool_iterations?: number
	workspace?: string
	//    ToolsConfig []byte `json:"tools_config,optional"`//    MemoryConfig []byte `json:"memory_config,optional"`//    CompactionConfig []byte `json:"compaction_config,optional"`//    OtherConfig []byte `json:"other_config,optional"`
	agent_description?: string
	emoji?: string
	thinking_level?: string
	max_tokens?: number
	self_evolve?: boolean
	skill_evolve?: boolean
	is_shared?: boolean
}
export interface UpdateAgentReqParams {
}

export interface UpdateAgentResp {
	agent: Agent
}

export interface UpdateBuiltinToolReq {
	enabled?: boolean
}
export interface UpdateBuiltinToolReqParams {
}

export interface UpdateBuiltinToolResp {
	status: string
}

export interface UpdateMCPServerReq {
	name?: string
	description?: string
	transport?: string
	command?: string
	args?: string
	url?: string
	headers?: string
	env?: string
	api_key?: string
	tool_prefix?: string
	timeout_sec?: number
	settings?: string
	enabled?: boolean
}
export interface UpdateMCPServerReqParams {
}

export interface UpdateMCPServerResp {
	server: MCPServer
}

export interface UpdateProviderReq {
	name?: string
	description?: string
	api_base?: string
	api_key?: string
	enabled?: boolean
}
export interface UpdateProviderReqParams {
}

export interface UpdateProviderResp {
	provider: Provider
}

export interface UpdateSkillReq {
	enabled?: boolean
	name?: string
	description?: string
	status?: string
	is_shared?: boolean
}
export interface UpdateSkillReqParams {
}

export interface UpdateSkillResp {
	skill: SkillResp
}

export interface UploadSkillReq {
}

export interface UploadSkillResp {
	id: number
	slug: string
	version: number
	name: string
	status: string
	is_new: boolean
	content_url: string
}

export interface UsageSummary {
	requests: number
	input_tokens: number
	output_tokens: number
	cost: number
	unique_users: number
	errors: number
	llm_calls: number
	tool_calls: number
	avg_duration_ms: number
}

export interface UsageTimeSeriesPoint {
	bucket_time: string
	request_count: number
	error_count: number
	unique_users: number
	input_tokens: number
	output_tokens: number
	total_cost: number
	llm_call_count: number
	tool_call_count: number
	avg_duration_ms: number
}

export interface UserResp {
	id: string
	email: string
	username: string
	created_at: number
}

export interface VerifyProviderReq {
	model: string
}
export interface VerifyProviderReqParams {
}

export interface VerifyProviderResp {
	valid: boolean
	error?: string
	note?: string
}

