package main

import (
	"fmt"
	"os"
	"time"

	"github.com/pomclaw/pomclaw/pkg/agent"
	storage "github.com/pomclaw/pomclaw/pkg/storage"
)

// seedDemoCmd populates the database with realistic demo data for demonstrations.
func seedDemoCmd() {
	cfg, err := loadConfig()
	if err != nil {
		fmt.Printf("Error loading config: %v\n", err)
		os.Exit(1)
	}

	storageType := cfg.StorageType
	if storageType == "" {
		storageType = "oracle"
	}

	// Determine which storage backend to use
	var isEnabled bool
	switch storageType {
	case "postgres":
		isEnabled = cfg.Postgres.Enabled
	case "oracle":
		isEnabled = cfg.Oracle.Enabled
	default:
		fmt.Printf("Unknown storage type: %s\n", storageType)
		os.Exit(1)
	}

	if !isEnabled {
		fmt.Printf("%s is not enabled in config. Set %s.enabled = true first.\n",
			storageType, storageType)
		os.Exit(1)
	}

	fmt.Printf("🌱 Seeding %s Database with demo data...\n", storageType)

	// Connect using factory
	conn, err := storage.NewConnectionManager(cfg)
	if err != nil {
		fmt.Printf("✗ Connection failed: %v\n", err)
		os.Exit(1)
	}
	defer conn.Close()
	fmt.Printf("✓ Connected to %s Database\n", storageType)

	db := conn.DB()

	// Create embedding service using factory
	embSvc, err := storage.NewEmbeddingService(cfg, db)
	if err != nil {
		fmt.Printf("✗ Failed to create embedding service: %v\n", err)
		os.Exit(1)
	}

	// --- Memories ---
	fmt.Print("  Seeding memories...")
	memoryStore := storage.NewMemoryStore(cfg, db, embSvc)

	memories := []struct {
		text       string
		importance float64
		category   string
	}{
		{"User prefers Oracle Database as the primary database. They work at Oracle and prefer Oracle AI Vector Search for embeddings.", 0.9, "preference"},
		{"Go is the user's primary programming language. They use Go 1.24 and target embedded Linux devices (RISC-V, ARM64, x86_64).", 0.85, "preference"},
		{"User prefers Ollama as the open-source LLM framework for local inference. Official docs at https://docs.ollama.com/", 0.8, "preference"},
		{"IMPORTANT: Never include AI attribution (Co-Authored-By, Generated by Claude, etc.) in git commit messages.", 0.9, "preference"},
		{"User prefers to push to GitHub manually. Only commit locally, never push automatically.", 0.85, "preference"},
		{"User is interested in RAG (Retrieval-Augmented Generation) using LlamaIndex and LangChain frameworks.", 0.7, "interest"},
		{"Pomclaw targets ultra-lightweight binaries (~10MB RAM) for embedded Linux devices including RISC-V boards.", 0.75, "preference"},
		{"User values privacy and data sovereignty. Prefers local/on-premise solutions over cloud-dependent services.", 0.8, "preference"},
		{"Pomclaw workspace is at ~/.pomclaw/workspace/ and config at ~/.pomclaw/config.json", 0.6, "fact"},
		{"The module path is github.com/pomclaw/pomclaw, forked from sipeed/pomclaw.", 0.7, "fact"},
		{"User prefers concise communication. Keep responses short and focused on implementation.", 0.75, "preference"},
		{"For complex multi-step tasks, use multi-agent parallel workflows. Prefer parallel agents over sequential work.", 0.65, "preference"},
		{"The Oracle ONNX embedding model used is ALL_MINILM_L12_V2 for in-database vector embeddings.", 0.7, "fact"},
		{"User is interested in IoT and embedded systems, particularly RISC-V and ARM64 development boards.", 0.6, "interest"},
		{"Design docs and plan files go in docs/plans/ (gitignored). Documentation is encouraged when beneficial.", 0.55, "preference"},
	}

	memoryErrors := 0
	for _, m := range memories {
		if _, err := memoryStore.Remember(m.text, m.importance, m.category); err != nil {
			memoryErrors++
		}
	}
	if memoryErrors == 0 {
		fmt.Printf(" ✓ %d memories stored\n", len(memories))
	} else {
		fmt.Printf(" ⚠ %d/%d memories stored (%d errors)\n", len(memories)-memoryErrors, len(memories), memoryErrors)
	}

	// Get agent ID from config
	agentID := storage.GetAgentID(cfg)

	// --- State entries ---
	fmt.Print("  Seeding state entries...")
	stateStore := storage.NewStateStore(cfg, db)

	stateEntries := map[string]string{
		"last_channel":       "cli",
		"last_chat_id":       "repl-session",
		"user_name":          "pomclaw",
		"user_timezone":      "America/Los_Angeles",
		"agent_mode":         "interactive",
		"total_conversations": "42",
		"tools_used_count":   "187",
		"last_model":         "gpt-4o-mini",
	}

	stateErrors := 0
	for k, v := range stateEntries {
		// Use specific state setters from the interface
		var err error
		switch k {
		case "last_channel":
			err = stateStore.SetLastChannel(v)
		case "last_chat_id":
			err = stateStore.SetLastChatID(v)
		// For other state values, we'd need additional methods in the interface
		default:
			// Skip non-interface state values for now
			continue
		}
		if err != nil {
			stateErrors++
		}
	}
	if stateErrors == 0 {
		fmt.Printf(" ✓ %d state entries stored\n", len(stateEntries))
	} else {
		fmt.Printf(" ⚠ %d/%d state entries stored (%d errors)\n", len(stateEntries)-stateErrors, len(stateEntries), stateErrors)
	}

	// --- Sessions with messages ---
	fmt.Print("  Seeding sessions...")
	sessionStore := storage.NewSessionStore(cfg, db)
	sessionStoreInterface := sessionStore.(agent.SessionManagerInterface)

	// Session 1: CLI REPL coding assistance
	sessionStoreInterface.AddMessage("cli:repl-session", "user", "Can you help me add a new tool to Pomclaw for monitoring I2C bus devices?")
	sessionStoreInterface.AddMessage("cli:repl-session", "assistant", "I can help with that. The tool should implement the `tools.Tool` interface from `pkg/tools/base.go`. You'll need `Name()`, `Description()`, `Parameters()`, and `Execute()` methods. Since I2C requires hardware access, the tool can read channel/chatID from context via `tools.ToolChannel(ctx)` and `tools.ToolChatID(ctx)` for proper error handling. Want me to scaffold the implementation?")
	sessionStoreInterface.AddMessage("cli:repl-session", "user", "Yes, please scaffold it. Make sure it works on RISC-V Linux.")
	sessionStoreInterface.AddMessage("cli:repl-session", "assistant", "Here's the I2C bus scanner tool. It uses `/dev/i2c-*` device files which are available on RISC-V Linux. The tool scans for connected devices and returns their addresses:\n\n```go\ntype I2CScanTool struct{}\n\nfunc (t *I2CScanTool) Name() string { return \"i2c_scan\" }\n```\n\nI've kept the binary size minimal by using only the standard library's `os` and `syscall` packages. No CGO required.")

	// Session 2: Telegram quick question
	sessionStoreInterface.AddMessage("telegram:user123", "user", "What's the status of the database connection?")
	sessionStoreInterface.AddMessage("telegram:user123", "assistant", "Database connection is active. Connected to the configured database with embedding service loaded. Current stats: 15 memories stored, 3 active sessions, 8 state entries.")

	// Session 3: Discord with tool usage
	sessionStoreInterface.AddMessage("discord:dev-channel", "user", "Remember that the next release should include WhatsApp channel support.")
	sessionStoreInterface.AddMessage("discord:dev-channel", "assistant", "I've stored that in memory. The next release should include WhatsApp channel support. I'll bring this up when we discuss release planning.")
	sessionStoreInterface.AddMessage("discord:dev-channel", "user", "What do you recall about our deployment targets?")
	sessionStoreInterface.AddMessage("discord:dev-channel", "assistant", "Based on my memories, your deployment targets include:\n1. Embedded Linux devices (RISC-V, ARM64, x86_64)\n2. Ultra-lightweight binaries (~10MB RAM)\n3. Self-contained single executable\n4. Multi-database support (Oracle and PostgreSQL)\n\nThe primary focus is on resource-constrained IoT devices.")

	sessionErrors := 0
	for _, key := range []string{"cli:repl-session", "telegram:user123", "discord:dev-channel"} {
		if err := sessionStore.Save(key); err != nil {
			sessionErrors++
		}
	}
	if sessionErrors == 0 {
		fmt.Println(" ✓ 3 sessions stored")
	} else {
		fmt.Printf(" ⚠ %d/3 sessions stored (%d errors)\n", 3-sessionErrors, sessionErrors)
	}

	// --- Daily notes ---
	fmt.Print("  Seeding daily notes...")
	dailyNoteErrors := 0

	// Today's note via AppendToday
	if err := memoryStore.AppendToday("## Development Progress\n- Implemented seed-demo command for database-agnostic data population\n- Tested vector embeddings with supported embedding models\n- Fixed session serialization edge case with empty tool calls"); err != nil {
		dailyNoteErrors++
	}

	// Note: Historical notes (yesterday, day before) would require raw SQL that differs between
	// Oracle and PostgreSQL. For now, we seed only today's note to keep the seed command simple
	// and database-agnostic. In production, use the memory store's Remember() or AppendToday() methods.

	if dailyNoteErrors == 0 {
		fmt.Println(" ✓ 1 daily note stored (today's note)")
	} else {
		fmt.Printf(" ⚠ %d/1 daily notes stored (%d errors)\n", 1-dailyNoteErrors, dailyNoteErrors)
	}

	// --- Config entries ---
	fmt.Print("  Seeding config entries...")
	configStoreRaw := storage.NewPromptStore(cfg, db)
	configStore, ok := configStoreRaw.(interface {
		SetConfigValue(key, value string) error
	})
	if !ok {
		// Skip config if the store doesn't have SetConfigValue method
		fmt.Println(" ⚠ Config store doesn't support SetConfigValue")
	} else {
		configJSON := `{
  "llm": {"provider": "openai-compatible", "model": "gpt-4o-mini", "base_url": "http://localhost:11434/v1"},
  "database": {"storage_type": "` + storageType + `"},
  "channels": {"telegram": {"enabled": true}, "discord": {"enabled": true}},
  "agent": {"max_tool_iterations": 10, "context_window": 8192}
}`

		configErrors := 0
		if err := configStore.SetConfigValue("full_config", configJSON); err != nil {
			configErrors++
		}
		if err := configStore.SetConfigValue("last_seed", time.Now().Format(time.RFC3339)); err != nil {
			configErrors++
		}
		if configErrors == 0 {
			fmt.Println(" ✓ 2 config entries stored")
		} else {
			fmt.Printf(" ⚠ %d/2 config entries stored (%d errors)\n", 2-configErrors, configErrors)
		}
	}

	// --- Transcripts ---
	fmt.Print("  Seeding transcripts...")
	transcripts := []struct {
		sessionKey string
		seqNum     int
		role       string
		content    string
	}{
		{"cli:repl-session", 1, "user", "Can you help me add a new tool to Pomclaw for monitoring I2C bus devices?"},
		{"cli:repl-session", 2, "assistant", "I can help with that. The tool should implement the tools.Tool interface from pkg/tools/base.go."},
		{"telegram:user123", 1, "user", "What's the status of the database connection?"},
		{"telegram:user123", 2, "assistant", "Database connection is active. Connected with embedding service loaded for vector search support."},
		{"discord:dev-channel", 1, "user", "Remember that the next release should include WhatsApp channel support."},
		{"discord:dev-channel", 2, "assistant", "I've stored that in memory. The next release should include WhatsApp channel support."},
	}

	transcriptErrors := 0
	for _, t := range transcripts {
		// Use database-agnostic parameterized query ($1, $2, etc. for PostgreSQL; :1, :2 for Oracle)
		// The database/sql package handles the conversion based on the driver
		var query string
		if storageType == "postgres" {
			query = `INSERT INTO POM_TRANSCRIPTS (session_key, agent_id, sequence_num, role, content)
					VALUES ($1, $2, $3, $4, $5)`
		} else {
			query = `INSERT INTO POM_TRANSCRIPTS (session_key, agent_id, sequence_num, role, content)
					VALUES (:1, :2, :3, :4, :5)`
		}
		_, err := db.Exec(query, t.sessionKey, agentID, t.seqNum, t.role, t.content)
		if err != nil {
			transcriptErrors++
		}
	}
	if transcriptErrors == 0 {
		fmt.Printf(" ✓ %d transcripts stored\n", len(transcripts))
	} else {
		fmt.Printf(" ⚠ %d/%d transcripts stored (%d errors)\n", len(transcripts)-transcriptErrors, len(transcripts), transcriptErrors)
	}

	fmt.Printf("\n🎉 Demo data seeded! Run 'pomclaw oracle-inspect' to see the populated %s dashboard.\n", storageType)
}
