export const ROUTES = {
  LOGIN: "/login",
  SELECT_TENANT: "/select-tenant",
  SETUP: "/setup",
  OVERVIEW: "/overview",
  CHAT: "/chat",
  CHAT_PATTERN: "/chat/:sessionKey?",
  AGENTS: "/agents",
  AGENT_DETAIL: "/agents/:id",
  AGENT_CODEX_POOL: "/agents/:id/codex-pool",
  PROVIDERS: "/providers",
  PROVIDER_DETAIL: "/providers/:id",
  API_KEYS: "/api-keys",
  TENANTS: "/admin/tenants",
  CONFIG: "/config",
  CHANNELS: "/channels",
  TTS: "/tts",
  CRON: "/cron",
  TRACES: "/traces",
  PACKAGES: "/packages",
  USAGE: "/usage",
  HOOKS: "/hooks",
} as const;
